# Usar una imagen oficial de Node.js como base
FROM node:22-bullseye-slim

# Crear y establecer el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json al contenedor
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar el resto de los archivos de la aplicación
COPY . .

# Establecer variables de entorno para el desarrollo
ENV NODE_ENV=development

# Exponer el puerto que usará la aplicación
EXPOSE 5173

# Comando para iniciar la aplicación en modo desarrollo
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
