openapi: 3.0.1
info:
  title: GDC External Api
  version: '${project.version}'
  description: Api to be implemented by an external application to be called by GDC.
basePath: /gdc
paths:
  /help/{idHelp}:
    post:
      tags:
      - help
      operationId: help
      description: Get help values depending on user values
      parameters:
      - name: idHelp
        description: ID of the help request
        in: path
        required: true
        schema:
          type: string
      - name: cmpVal
        in: query
        description: Company code
        required: false
        type: integer 
      requestBody:
        required: true
        description: Data input including user form and user info
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/DataIn'
      responses:
        200:
          description: OK response
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HelpValue'
  /validation/{idConcept}/field/{idField}:
    post:
      tags:
      - validation
      operationId: fieldValidation
      description: Validate a field
      parameters:
      - name: idConcept
        description: Concept ID
        in: path
        required: true
        schema:
          type: string
      - name: idField
        description: Field ID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        description: Data input including user form and user info
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/DataIn'
      responses:
        200:
          description: default response
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ValidationError'
  /validation/{idConcept}:
    post:
      tags:
      - validation
      operationId: conceptValidation
      description: Validate a concept
      parameters:
      - name: idConcept
        description: Concept ID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        description: Data input including user form and user info
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/DataInExtended'
      responses:
        200:
          description: OK response
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ValidationError'
  /validation/flow/{idFlow}:
    post:
      tags:
      - validation
      operationId: flowValidation
      description: Validate a flow
      parameters:
      - name: idFlow
        description: Flow ID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        description: Data input including user form and user info
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/DataIn'
      responses:
        200:
          description: OK response
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ValidationError'
  /default/{idConcept}/field/{idField}:
    post:
      tags:
      - default
      operationId: defaultValue
      description: Get the default value for a field
      parameters:
      - name: idConcept
        description: Concept ID
        in: path
        required: true
        schema:
          type: string
      - name: idField
        description: Field ID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        description: Data input including user info
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/DataIn'
      responses:
        200:
          description: OK response
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/DefaultValue'
  /composition/{idComposition}/{ídStep}/previous:
    post:
      tags:
      - composition
      operationId: compositionPrevious
      description: Load initial data into a composition step
      parameters:
      - name: idComposition
        description: Composition ID
        in: path
        required: true
        schema:
          type: string
      - name: ídStep
        description: Step ID in the Composition
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        description: Data input including user info
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/DataIn'
      responses:
        200:
          description: OK response
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/CompositionOut'
  /composition/{idComposition}/{ídStep}/finish:
    post:
      tags:
      - composition
      operationId: compositionFinish
      description: Performs an the finish step action in a composition step
      parameters:
      - name: idComposition
        description: Composition ID
        in: path
        required: true
        schema:
          type: string
      - name: ídStep
        description: Step ID in the Composition
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        description: Data input including user info and screen data
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CompositionIn'
      responses:
        200:
          description: OK response
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/CompositionOut'
  /composition/{idComposition}/{ídStep}/action:
    post:
      tags:
      - composition
      operationId: compositionAction
      description: Performs an action in a composition step
      parameters:
      - name: idComposition
        description: Composition ID
        in: path
        required: true
        schema:
          type: string
      - name: ídStep
        description: Step ID in the Composition
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        description: Data input including user info, action info and screen data
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CompositionActionIn'
      responses:
        200:
          description: OK response
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/CompositionOut'
  /composition/{idComposition}/{ídStep}/exit:
    post:
      tags:
      - composition
      operationId: compositionExit
      description: Performs an the exit action in a composition
      parameters:
      - name: idComposition
        description: Composition ID
        in: path
        required: true
        schema:
          type: string
      - name: ídStep
        description: Step ID in the Composition
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        description: Data input including user info
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CompositionIn'
      responses:
        200:
          description: OK response
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/CompositionOut'
components:
  schemas:
    UserInfo:
      description: Data of the user
      type: object
      properties:
        id:
          description: id of the user
          type: string
        company:
          description: company of the user
          type: integer
        language:
          description: language of the user
          type: string
    DataIn:
      description: Data for a request
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserInfo'
        data:
          description: User form
          type: object
          additionalProperties:
            type: string
    DataInExtended:
      description: Extended data for a concept validation request inluding original value
      allOf:     # Combines the DataIn
        - $ref: '#/components/schemas/DataIn'
        - type: object
          properties:
            dataOld:
              description: Original updating data
              type: object
              additionalProperties:
                type: string
    HelpValue:
      description: Help value
      type: object
      properties:
        code:
          description: Help value code
          type: string
        label:
          description: Help value label
          type: string
        custom:
          description:  Extended custom values
          type: object
          additionalProperties:
            type: string
    ValidationError:
      description: Validation error of a filed or a concept
      type: object
      properties:
        code:
          description: Error code
          type: string
        field:
          description: Field code
          type: string
        value:
          description: Value of the field
          type: string
        format:
          description: Error condition (max value, min value, ...)
          type: string
        vformat:
          description: Value for the error condition (max value, min value, ...)
          type: string
    DefaultValue:
      description: Default value for a field
      type: object
      properties:
        value:
          description: Default value
          type: string
    CompositionFieldMetadata:
      description: Metadata for a filed in a concept change default configuration
      type: object 
      properties:
        vsb:
          description: Change visible condition of the field
          type: boolean
        mdf:
          description: Change modifiable condition of the field
          type: boolean
        obl:
          description: Change obligatory condition of the field
          type: boolean
    CompositionValueMetadata:
      description: Metadata for a concept in a composition
      type: object 
      properties:
        cpoIdn:
          description: Unique id of the concept
          type: string
        oprStsTypVal:
          description: State of the concept
          type: integer
        prc:
          description: Process data
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CompositionFieldMetadata'
        custom:
          description: Free data to pass from logic to presentation
          type: object
          additionalProperties:
            type: string
    CompositionValue:
      description: Value for a concept in a composition
      type: object 
      properties:
        info:
          description: Metatada
          $ref: '#/components/schemas/CompositionValueMetadata'
        data:
          description: Screen data
          type: array
          items:
            type: object
            additionalProperties:
              type: string
    CompositionIn:
      description: Data for a request
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserInfo'
        data:
          description: Screen data
          type: array
          items:
            $ref: '#/components/schemas/CompositionValue'
    CompositionActionIn:
      description: Data for an action request
      allOf:     # Combines the CompositionIn
        - $ref: '#/components/schemas/CompositionIn'
        - type: object
          properties:
            cpoIdn:
              description: Unique id of the origin concept
              type: string
            action:
              description: Unique id of the action
              type: string
    CompositionError:
      description: Error data
      type: object
      properties:
        cpoIdn:
          description: Unique id of the origin concept that causes the error
          type: string
        errNam:
          description: Error message
          type: string
        errVal:
          description: Error aditional info
          type: string
        prpNam:
          description: Field that causes the error
          type: string
    CompositionMessage:
      description: Data for a message with an aditional action in a cancel/accept option
      type: object
      properties:
        message:
          description: Message
          type: string
        type:
          description: Message type (success, info, warning)
          type: string
        action:
          description: Action ID
          type: string
    CompositionOut:
        description: Data for a response
        type: object
        properties:
          errors:
            description: Return information for errors
            type: array
            items:
              $ref: '#/components/schemas/CompositionError'
          message:
            description: Return information for message and aditional actions
            $ref: '#/components/schemas/CompositionMessage'
          urlRedirectAction:
            description: URL for redirect
            type: string
          nextStep:
            description: Skip flow until next step
            type: integer
          data:
            description: Output data
            type: array
            items:
              $ref: '#/components/schemas/CompositionValue'

