/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.tron.api.cmn.model.About;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "about", description = "the about API")
@RequestMapping(value = "/newtron/api/common")
public interface AboutApi {

    Logger log = LoggerFactory.getLogger(AboutApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query about application", nickname = "getAboutQuery", notes = "Query Query about application. It will return the information about the deployed application.", response = About.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Settings", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The information about the deployed application", response = About.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/about/query",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<About> getAboutQuery(@ApiParam(value = "Company code" ) @RequestHeader(value="cmpVal", required=false) Integer cmpVal,@ApiParam(value = "User code" ) @RequestHeader(value="usrVal", required=false) String usrVal,@ApiParam(value = "Language code" ) @RequestHeader(value="lngVal", required=false) String lngVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"profile\" : \"Newtron access\",  \"name\" : \"nwt_lss_api_be:20.07.03-SNAPSHOT\",  \"dependencies\" : \"nwt_cmn_api_be:20.07.03-SNAPSHOT\"}", About.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default AboutApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
