/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.ard.abv.bo.OArdAbvS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "attributeValues", description = "the attributeValues API")
@RequestMapping(value = "/newtron/api/common")
public interface AttributeValuesApi {

    Logger log = LoggerFactory.getLogger(AttributeValuesApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query Attribute Values", nickname = "getAttributeValues", notes = "Query attribute values. It will return the values of the variable data.  It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = OArdAbvS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Attribute value List", response = OArdAbvS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/attributeValues",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OArdAbvS>> getAttributeValues(@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@NotNull @ApiParam(value = "Company", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Field code", required = true) @Valid @RequestParam(value = "fldNam", required = true) String fldNam,@ApiParam(value = "Line of Business") @Valid @RequestParam(value = "lobVal", required = false) Integer lobVal,@ApiParam(value = "Modality") @Valid @RequestParam(value = "mdtVal", required = false) Integer mdtVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"fldNam\" : \"fldNam\",  \"mdtVal\" : 1.46581298050294517310021547018550336360931396484375,  \"fldTxtVal\" : \"fldTxtVal\",  \"valVal\" : \"valVal\",  \"vldDat\" : 5,  \"lobVal\" : 6.02745618307040320615897144307382404804229736328125,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdtNam\" : \"mdtNam\",  \"ponVal\" : 5.962133916683182377482808078639209270477294921875,  \"lobNam\" : \"lobNam\"}, {  \"fldNam\" : \"fldNam\",  \"mdtVal\" : 1.46581298050294517310021547018550336360931396484375,  \"fldTxtVal\" : \"fldTxtVal\",  \"valVal\" : \"valVal\",  \"vldDat\" : 5,  \"lobVal\" : 6.02745618307040320615897144307382404804229736328125,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdtNam\" : \"mdtNam\",  \"ponVal\" : 5.962133916683182377482808078639209270477294921875,  \"lobNam\" : \"lobNam\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default AttributeValuesApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
