/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.cmn.typ.bo.OCmnTypP;
import com.mapfre.nwt.trn.rcd.tmd.bo.ORcdTmdS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "CollectorTypes", description = "the CollectorTypes API")
@RequestMapping(value = "/newtron/api/common")
public interface CollectorTypesApi {

    Logger log = LoggerFactory.getLogger(CollectorTypesApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query Collector Types v1", nickname = "getCollectorTypeV1", notes = "Query collector type v1. It will return the type of collector. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = ORcdTmdS.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Collection manager definition List", response = ORcdTmdS.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/CollectorTypes/1.0/{mnrTypVal}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<ORcdTmdS> getCollectorTypeV1(@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@ApiParam(value = "Collector Type",required=true) @PathVariable("mnrTypVal") String mnrTypVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"ctmTypNam\" : \"ctmTypNam\",  \"pgmVal\" : \"pgmVal\",  \"ctmCssTypVal\" : \"ctmCssTypVal\",  \"mdfDat\" : 0,  \"mnrTypVal\" : \"mnrTypVal\",  \"vldPgmNam\" : \"vldPgmNam\",  \"ctmCssTypNam\" : \"ctmCssTypNam\",  \"usrVal\" : \"usrVal\",  \"thpRskCll\" : \"thpRskCll\"}", ORcdTmdS.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default CollectorTypesApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Query Collector Types", nickname = "getCollectorTypes", notes = "Query collector types. It will return the types of collector. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = OCmnTypP.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Type List", response = OCmnTypP.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/CollectorTypes",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OCmnTypP>> getCollectorTypes(@ApiParam(value = "User code" ,required=true) @RequestHeader(value="usrVal", required=true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@ApiParam(value = "Company code") @Valid @RequestParam(value = "cmpVal", required = false) Integer cmpVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"oCmnTypS\" : {    \"fldNam\" : \"fldNam\",    \"itcVal\" : \"itcVal\",    \"lngVal\" : \"lngVal\",    \"btcPrcVal\" : 0.80082819046101150206595775671303272247314453125,    \"itcNam\" : \"itcNam\"  }}, {  \"oCmnTypS\" : {    \"fldNam\" : \"fldNam\",    \"itcVal\" : \"itcVal\",    \"lngVal\" : \"lngVal\",    \"btcPrcVal\" : 0.80082819046101150206595775671303272247314453125,    \"itcNam\" : \"itcNam\"  }} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default CollectorTypesApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Query Collector Types v1", nickname = "getCollectorTypesV1", notes = "Query collector types v1. It will return the types of collector. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = ORcdTmdS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Collection manager definition List", response = ORcdTmdS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/CollectorTypes/1.0",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<ORcdTmdS>> getCollectorTypesV1(@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@ApiParam(value = "Company code") @Valid @RequestParam(value = "cmpVal", required = false) Integer cmpVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"ctmTypNam\" : \"ctmTypNam\",  \"pgmVal\" : \"pgmVal\",  \"ctmCssTypVal\" : \"ctmCssTypVal\",  \"mdfDat\" : 0,  \"mnrTypVal\" : \"mnrTypVal\",  \"vldPgmNam\" : \"vldPgmNam\",  \"ctmCssTypNam\" : \"ctmCssTypNam\",  \"usrVal\" : \"usrVal\",  \"thpRskCll\" : \"thpRskCll\"}, {  \"ctmTypNam\" : \"ctmTypNam\",  \"pgmVal\" : \"pgmVal\",  \"ctmCssTypVal\" : \"ctmCssTypVal\",  \"mdfDat\" : 0,  \"mnrTypVal\" : \"mnrTypVal\",  \"vldPgmNam\" : \"vldPgmNam\",  \"ctmCssTypNam\" : \"ctmCssTypNam\",  \"usrVal\" : \"usrVal\",  \"thpRskCll\" : \"thpRskCll\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default CollectorTypesApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
