/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import com.mapfre.tron.api.cmn.model.FavoritesDto;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

@Api(value = "favorites", description = "the favorites API")
@RequestMapping(value = "/newtron/api/common")
public interface FavoritesApi {

    Logger log = LoggerFactory.getLogger(FavoritesApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "User favorites", nickname = "deleteFavoritesList", notes = "Delete a user favorite of determined by company.  It will be deleted from db.", response = FavoritesDto.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Favorite deleted", response = FavoritesDto.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/favorites/{cmpVal}/{usrVal}/{oprIdnVal}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    default ResponseEntity<List<FavoritesDto>> deleteFavoritesList(@ApiParam(value = "Company code",required=true) @PathVariable("cmpVal") BigDecimal cmpVal,@ApiParam(value = "Username",required=true) @PathVariable("usrVal") String usrVal,@ApiParam(value = "Operation identifier",required=true) @PathVariable("oprIdnVal") String oprIdnVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"oprIdnVal\" : \"oprIdnVal\"}, {  \"oprIdnVal\" : \"oprIdnVal\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default FavoritesApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "User favorites", nickname = "getFavoritesList", notes = "Query user favorites by company and user. It will return the favorites of an user. It will be mandatory send the parameters defined in the url.", response = FavoritesDto.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Favorites List", response = FavoritesDto.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/favorites/{cmpVal}/{usrVal}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<FavoritesDto>> getFavoritesList(@ApiParam(value = "Company code",required=true) @PathVariable("cmpVal") BigDecimal cmpVal,@ApiParam(value = "Username",required=true) @PathVariable("usrVal") String usrVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"oprIdnVal\" : \"oprIdnVal\"}, {  \"oprIdnVal\" : \"oprIdnVal\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default FavoritesApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "User favorites", nickname = "postFavoritesList", notes = "Post a new user favorite of user determined by company.  It will be saved on database", response = FavoritesDto.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Favorite saved", response = FavoritesDto.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/favorites/{cmpVal}/{usrVal}/{oprIdnVal}",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<List<FavoritesDto>> postFavoritesList(@ApiParam(value = "Company code",required=true) @PathVariable("cmpVal") BigDecimal cmpVal,@ApiParam(value = "Username",required=true) @PathVariable("usrVal") String usrVal,@ApiParam(value = "Operation identifier",required=true) @PathVariable("oprIdnVal") String oprIdnVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"oprIdnVal\" : \"oprIdnVal\"}, {  \"oprIdnVal\" : \"oprIdnVal\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default FavoritesApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
