/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.lsf.fid.bo.OLsfFidS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "fileTypeDefinition", description = "the fileTypeDefinition API")
@RequestMapping(value = "/newtron/api/common")
public interface FileTypeDefinitionApi {

    Logger log = LoggerFactory.getLogger(FileTypeDefinitionApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query file type definition", nickname = "getFileTypeDefinition", notes = "Query file type definition. It will return the definition of a type of file", response = OLsfFidS.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "File", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "File type defintion", response = OLsfFidS.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/fileTypeDefinition/{filTypVal}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<OLsfFidS> getFileTypeDefinition(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@ApiParam(value = "File Type Value",required=true) @PathVariable("filTypVal") String filTypVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"dsbRow\" : \"dsbRow\",  \"adjVltPgmPrdNam\" : \"adjVltPgmPrdNam\",  \"rsvCncNam\" : \"rsvCncNam\",  \"filTypVal\" : \"filTypVal\",  \"filTypNam\" : \"filTypNam\",  \"plnVal\" : \"plnVal\",  \"rsvCncVal\" : 5.962133916683182377482808078639209270477294921875,  \"atmOpgPrdNam\" : \"atmOpgPrdNam\",  \"psbLsaRpn\" : \"psbLsaRpn\",  \"stuVal\" : \"stuVal\",  \"rsvCncTypVal\" : \"rsvCncTypVal\",  \"lobFilOpgRsn\" : \"lobFilOpgRsn\",  \"pemPsvRcyTypVal\" : \"pemPsvRcyTypVal\",  \"crnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"filGrgTypVal\" : \"filGrgTypVal\",  \"getLopPrdNam\" : \"getLopPrdNam\",  \"stuCodPrdNam\" : \"stuCodPrdNam\",  \"unqCrn\" : \"unqCrn\",  \"filTypRcy\" : \"filTypRcy\",  \"lsaRqr\" : \"lsaRqr\",  \"atmOpg\" : \"atmOpg\",  \"rcyVltAstFilPrdNam\" : \"rcyVltAstFilPrdNam\",  \"exsMip\" : \"exsMip\",  \"atmNtcPrdNam\" : \"atmNtcPrdNam\",  \"exsTrl\" : \"exsTrl\",  \"filTypPsv\" : \"filTypPsv\",  \"ownTypVal\" : \"ownTypVal\",  \"atmOpgFilValPrdNam\" : \"atmOpgFilValPrdNam\",  \"unqLsaRqt\" : \"unqLsaRqt\",  \"useIno\" : \"useIno\",  \"exlFilTypVal\" : \"exlFilTypVal\",  \"filRsvCll\" : \"filRsvCll\",  \"rcyAfdFilTypVal\" : \"rcyAfdFilTypVal\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"rcyFilTypVal\" : \"rcyFilTypVal\",  \"lssPrc\" : \"lssPrc\",  \"pemAdjVlt\" : \"pemAdjVlt\",  \"lsaPsb\" : \"lsaPsb\",  \"pemPsvRcyPrdNam\" : \"pemPsvRcyPrdNam\",  \"mulTrl\" : \"mulTrl\",  \"plnCodPrdNam\" : \"plnCodPrdNam\",  \"qryStuVal\" : \"qryStuVal\",  \"pndLsa\" : \"pndLsa\",  \"rqrLsaPrdNam\" : \"rqrLsaPrdNam\",  \"rqtStsVal\" : \"rqtStsVal\",  \"daaStuVal\" : \"daaStuVal\",  \"rsvCllPrdNam\" : \"rsvCllPrdNam\",  \"lobVal\" : 1.46581298050294517310021547018550336360931396484375,  \"rcyVltAstFilTypVal\" : \"rcyVltAstFilTypVal\",  \"unq\" : \"unq\"}", OLsfFidS.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default FileTypeDefinitionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
