/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.thp.cnt.bo.OThpCntS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "firstLevel", description = "the firstLevel API")
@RequestMapping(value = "/newtron/api/common")
public interface FirstLevelApi {

    Logger log = LoggerFactory.getLogger(FirstLevelApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query Contact From First Level", nickname = "getContactFromFirstLevel", notes = "Query the first level contact information. It will return the contact of the first level of the commercial structure . It will be mandatory send  the parameters defined in the service and the service will response with the output object defined.", response = OThpCntS.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Contact Information", response = OThpCntS.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/firstLevel/{frsLvlVal}/contact",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<OThpCntS> getContactFromFirstLevel(
	    @NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,
	    @ApiParam(value = "Language code", required = true) @RequestHeader(value = "lngVal", required = true) String lngVal,
	    @NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,
	    @ApiParam(value = "First Level", required = true) @PathVariable("frsLvlVal") Integer frsLvlVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"emlAdr\" : \"emlAdr\",  \"tlpCnyCck\" : \"tlpCnyCck\",  \"thpAcvVal\" : 2.3021358869347654518833223846741020679473876953125,  \"clrTlpCck\" : \"clrTlpCck\",  \"cntPrsNtnVal\" : \"cntPrsNtnVal\",  \"bprVal\" : \"bprVal\",  \"mdfScoVal\" : \"mdfScoVal\",  \"cntPrsNtnTypNam\" : \"cntPrsNtnTypNam\",  \"cntPrsSrn\" : \"cntPrsSrn\",  \"tlpVal\" : \"tlpVal\",  \"areClrTlpVal\" : \"areClrTlpVal\",  \"tlpExtVal\" : \"tlpExtVal\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdfDat\" : 1,  \"faxVal\" : \"faxVal\",  \"pstTypVal\" : \"pstTypVal\",  \"sqnVal\" : 5.63737665663332876420099637471139430999755859375,  \"thpVal\" : 7.061401241503109105224211816675961017608642578125,  \"bprCck\" : \"bprCck\",  \"cnyClrTlpVal\" : \"cnyClrTlpVal\",  \"pstTypNam\" : \"pstTypNam\",  \"tlpAreVal\" : \"tlpAreVal\",  \"cntTypVal\" : \"cntTypVal\",  \"ecmAcvTypNam\" : \"ecmAcvTypNam\",  \"emlAdrCck\" : \"emlAdrCck\",  \"cntTypNam\" : \"cntTypNam\",  \"thpDcmVal\" : \"thpDcmVal\",  \"clrTlpVal\" : \"clrTlpVal\",  \"plyVal\" : \"plyVal\",  \"thpDcmTypVal\" : \"thpDcmTypVal\",  \"ecmAcvTypVal\" : \"ecmAcvTypVal\",  \"faxCck\" : \"faxCck\",  \"vldDat\" : 9,  \"cntPrsNam\" : \"cntPrsNam\",  \"rskVal\" : 5.962133916683182377482808078639209270477294921875,  \"enrSqn\" : 6.02745618307040320615897144307382404804229736328125,  \"acnOrgVal\" : \"acnOrgVal\",  \"tlpCnyVal\" : \"tlpCnyVal\"}", OThpCntS.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default FirstLevelApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
