/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.dsr.fdc.bo.ODsrFdcS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "firstLevelDistributionChannelByCmp", description = "the firstLevelDistributionChannelByCmp API")
@RequestMapping(value = "/newtron/api/common")
public interface FirstLevelDistributionChannelByCmpApi {

    Logger log = LoggerFactory.getLogger(FirstLevelDistributionChannelByCmpApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "First Level Distribution Channel by Company", nickname = "getfirstLevelDistributionChannelByCmp", notes = "Query First Level Distribution Channel by company. It will return the types of languages. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = ODsrFdcS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Language List", response = ODsrFdcS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/firstLevelDistributionChannelByCmp",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<ODsrFdcS>> getfirstLevelDistributionChannelByCmp(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"frsDstHnlNam\" : \"frsDstHnlNam\",  \"dsbRow\" : \"dsbRow\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"frsDstHnlAbr\" : \"frsDstHnlAbr\",  \"frsDstHnlVal\" : \"frsDstHnlVal\"}, {  \"frsDstHnlNam\" : \"frsDstHnlNam\",  \"dsbRow\" : \"dsbRow\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"frsDstHnlAbr\" : \"frsDstHnlAbr\",  \"frsDstHnlVal\" : \"frsDstHnlVal\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default FirstLevelDistributionChannelByCmpApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "First Level Distribution Channel by Company", nickname = "getfirstLevelDistributionChannelByCmpById", notes = "Query First Level Distribution Channel by company. It will return the types of languages. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = ODsrFdcS.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "First level distribution channel", response = ODsrFdcS.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/firstLevelDistributionChannelByCmp/{frsDstHnlVal}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<ODsrFdcS> getfirstLevelDistributionChannelByCmpById(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "First level distribution channel",required=true) @PathVariable("frsDstHnlVal") String frsDstHnlVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"frsDstHnlNam\" : \"frsDstHnlNam\",  \"dsbRow\" : \"dsbRow\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"frsDstHnlAbr\" : \"frsDstHnlAbr\",  \"frsDstHnlVal\" : \"frsDstHnlVal\"}", ODsrFdcS.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default FirstLevelDistributionChannelByCmpApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
