/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import com.mapfre.tron.api.bo.Error;
import com.mapfre.tron.api.cmn.model.MenuDto;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.Optional;

@Api(value = "menu", description = "the menu API")
@RequestMapping(value = "/newtron/api/common")
public interface MenuApi {

    Logger log = LoggerFactory.getLogger(MenuApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query Newtron Menu", nickname = "getMenu", notes = "Query Newtron Menu. It will return the Headers and the list of menu points.", response = MenuDto.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Menu", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Menu List", response = MenuDto.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/menu",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<MenuDto> getMenu(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Language code", required = true) @Valid @RequestParam(value = "lngVal", required = true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"header\" : [ {    \"oprIdnVal\" : \"a\",    \"oprIdnNam\" : \"descripcion\",    \"funOprUrl\" : \"http://abc/de\",    \"pgmDsb\" : \"N\",    \"menSqnVal\" : 1  } ],  \"list\" : [ {    \"agrValPrn\" : \"newtron\",    \"oprIdnVal\" : \"a\",    \"oprIdnNam\" : \"descripcion\",    \"funOprUrl\" : \"http://abc/de\",    \"pgmDsb\" : \"N\",    \"menSqnVal\" : 1  } ]}", MenuDto.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default MenuApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
