/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.cmn.mvr.bo.OCmnMvrS;
import com.mapfre.nwt.trn.trn.vrb.bo.OTrnVrbS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "movementRecord", description = "the movementRecord API")
@RequestMapping(value = "/newtron/api/common")
public interface MovementRecordApi {

    Logger log = LoggerFactory.getLogger(MovementRecordApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Create movement record for a third party", nickname = "postMovementRecordList", notes = "Create or update movement record. It will create a new movement record of a third party. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Movement Record", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Operation succesfully done!"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/movementRecord",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> postMovementRecordList(@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Document type", required = true) @Valid @RequestParam(value = "thpDcmTypVal", required = true) String thpDcmTypVal,@NotNull @ApiParam(value = "Document", required = true) @Valid @RequestParam(value = "thpDcmVal", required = true) String thpDcmVal,@NotNull @ApiParam(value = "Activity", required = true) @Valid @RequestParam(value = "thpAcvVal", required = true) Integer thpAcvVal,@ApiParam(value = "Input data to new movement record" ,required=true )  @Valid @RequestBody OCmnMvrS inMovementRecord) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default MovementRecordApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Retrieve movement record by note value", nickname = "postMovementRecordbyNote", notes = "Retrieve movement record by note value", response = OCmnMvrS.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Movement Record", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Movement Record List", response = OCmnMvrS.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Uncontrolled error", response = Error.class) })
    @RequestMapping(value = "/movementRecord/MovementRecordbyNote",
        method = RequestMethod.POST)
    default ResponseEntity<OCmnMvrS> postMovementRecordbyNote(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) BigDecimal cmpVal,@NotNull @ApiParam(value = "Note Value", required = true) @Valid @RequestParam(value = "nteVal", required = true) String nteVal,@NotNull @ApiParam(value = "Movement Identification", required = true) @Valid @RequestParam(value = "mvmldn", required = true) String mvmldn,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Input data global variables"  )  @Valid @RequestBody List<OTrnVrbS> oTrnVrbT) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"mvmSucIdn\" : \"mvmSucIdn\",  \"mvmRsnIdn\" : \"mvmRsnIdn\",  \"thrDstHnlVal\" : \"thrDstHnlVal\",  \"rskIdn\" : \"rskIdn\",  \"mvmSttDat\" : 5,  \"mvmPbl\" : \"mvmPbl\",  \"etcVal\" : \"etcVal\",  \"mvmSttTypNam\" : \"mvmSttTypNam\",  \"dspVal\" : \"dspVal\",  \"pymOrdVal\" : 2.3021358869347654518833223846741020679473876953125,  \"stsTypVal\" : \"stsTypVal\",  \"mvmPrcNam\" : \"mvmPrcNam\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"mvmIdn\" : \"mvmIdn\",  \"qtnVal\" : \"qtnVal\",  \"lssVal\" : \"lssVal\",  \"agrValPrn\" : \"agrValPrn\",  \"mvmDat\" : 1,  \"errTxtVal\" : \"errTxtVal\",  \"prcTypVal\" : \"prcTypVal\",  \"mvmSucNam\" : \"mvmSucNam\",  \"plyVal\" : \"plyVal\",  \"rcpVal\" : 5.63737665663332876420099637471139430999755859375,  \"titVal\" : \"titVal\",  \"mvmSttTypVal\" : \"mvmSttTypVal\",  \"mvmTme\" : \"mvmTme\",  \"rskVal\" : 7.061401241503109105224211816675961017608642578125,  \"thrDstHnlNam\" : \"thrDstHnlNam\",  \"mvmPrcIdn\" : \"mvmPrcIdn\",  \"mvmRsnNam\" : \"mvmRsnNam\"}", OCmnMvrS.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default MovementRecordApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Searcher and register supplier's notifications", nickname = "putSupplierNotificationComplete", notes = "Searcher and register supplier's notifications", response = String.class, tags={ "Movement Record", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operation successfully done without notifications!", response = String.class),
        @ApiResponse(code = 201, message = "Operation successfully done!", response = String.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Uncontrolled error", response = Error.class) })
    @RequestMapping(value = "/movementRecord/supplierNotificationComplete",
        method = RequestMethod.PUT)
    default ResponseEntity<String> putSupplierNotificationComplete(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) BigDecimal cmpVal,@NotNull @ApiParam(value = "User value", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "Third party activity value", required = true) @Valid @RequestParam(value = "thpAcvVal", required = true) Integer thpAcvVal,@NotNull @ApiParam(value = "Third person document type value", required = true) @Valid @RequestParam(value = "thpDcmTypVal", required = true) String thpDcmTypVal,@NotNull @ApiParam(value = "Third person document number", required = true) @Valid @RequestParam(value = "thpDcmVal", required = true) String thpDcmVal,@NotNull @ApiParam(value = "Operation", required = true) @Valid @RequestParam(value = "oprIdnVal", required = true) String oprIdnVal,@NotNull @ApiParam(value = "Generation type value", required = true) @Valid @RequestParam(value = "gnrTypVal", required = true) String gnrTypVal,@ApiParam(value = "Service order") @Valid @RequestParam(value = "svoVal", required = false) String svoVal,@ApiParam(value = "Service") @Valid @RequestParam(value = "sswVal", required = false) Integer sswVal,@ApiParam(value = "Loss value") @Valid @RequestParam(value = "lssVal", required = false) BigDecimal lssVal,@ApiParam(value = "Policy value") @Valid @RequestParam(value = "plyVal", required = false) String plyVal,@ApiParam(value = "Risk value") @Valid @RequestParam(value = "rskVal", required = false) Integer rskVal,@ApiParam(value = "Input data global variables"  )  @Valid @RequestBody List<OTrnVrbS> oTrnVrbT) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("\"\"", String.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default MovementRecordApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
