/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.cmn.mvr.bo.OCmnMvrS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "movementsRecord", description = "the movementsRecord API")
@RequestMapping(value = "/newtron/api/common")
public interface MovementsRecordApi {

    Logger log = LoggerFactory.getLogger(MovementsRecordApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query movements record by third party", nickname = "getMovementRecordList", notes = "Query movements record by third party. It will return the movements record of a third party. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = OCmnMvrS.class, responseContainer = "List", authorizations = {
	        @Authorization(value = "basicAuth")
	    }, tags={ "Movement Record", })
	    @ApiResponses(value = { 
	        @ApiResponse(code = 200, message = "Movement Record List", response = OCmnMvrS.class, responseContainer = "List"),
	        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
	        @ApiResponse(code = 404, message = "Not found", response = Error.class),
	        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
	    @RequestMapping(value = "/movementsRecord/queryByThp",
	        produces = { "application/json" }, 
	        method = RequestMethod.GET)
	    default ResponseEntity<List<OCmnMvrS>> getMovementRecordList(@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Document type", required = true) @Valid @RequestParam(value = "thpDcmTypVal", required = true) String thpDcmTypVal,@NotNull @ApiParam(value = "document", required = true) @Valid @RequestParam(value = "thpDcmVal", required = true) String thpDcmVal,@NotNull @ApiParam(value = "Activity", required = true) @Valid @RequestParam(value = "thpAcvVal", required = true) Integer thpAcvVal,@NotNull @ApiParam(value = "Movement Identification", required = true) @Valid @RequestParam(value = "mvmIdn", required = true) List<String> mvmIdn,@ApiParam(value = "Query Date") @Valid @RequestParam(value = "qryDat", required = false) Long qryDat,@ApiParam(value = "Movement state type") @Valid @RequestParam(value = "mvmSttTypVal", required = false) String mvmSttTypVal,@ApiParam(value = "Public Movement") @Valid @RequestParam(value = "mvmPbl", required = false) String mvmPbl,@ApiParam(value = "Status Type Value") @Valid @RequestParam(value = "stsTypVal", required = false) List<String> stsTypVal,@ApiParam(value = "Process Type value") @Valid @RequestParam(value = "prcTypVal", required = false) String prcTypVal) {
	        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
	            if (getAcceptHeader().get().contains("application/json")) {
	                try {
	                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"lssVal\" : \"lssVal\",  \"mvmSucIdn\" : \"mvmSucIdn\",  \"mvmRsnIdn\" : \"mvmRsnIdn\",  \"mvmDat\" : 1,  \"thrDstHnlVal\" : \"thrDstHnlVal\",  \"rskIdn\" : \"rskIdn\",  \"mvmSttDat\" : 5,  \"mvmPbl\" : \"mvmPbl\",  \"mvmSucNam\" : \"mvmSucNam\",  \"mvmSttTypNam\" : \"mvmSttTypNam\",  \"plyVal\" : \"plyVal\",  \"rcpVal\" : 5.63737665663332876420099637471139430999755859375,  \"pymOrdVal\" : 2.3021358869347654518833223846741020679473876953125,  \"mvmPrcNam\" : \"mvmPrcNam\",  \"mvmSttTypVal\" : \"mvmSttTypVal\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"mvmTme\" : \"mvmTme\",  \"thrDstHnlNam\" : \"thrDstHnlNam\",  \"mvmPrcIdn\" : \"mvmPrcIdn\",  \"mvmRsnNam\" : \"mvmRsnNam\",  \"mvmIdn\" : \"mvmIdn\",  \"qtnVal\" : \"qtnVal\"}, {  \"lssVal\" : \"lssVal\",  \"mvmSucIdn\" : \"mvmSucIdn\",  \"mvmRsnIdn\" : \"mvmRsnIdn\",  \"mvmDat\" : 1,  \"thrDstHnlVal\" : \"thrDstHnlVal\",  \"rskIdn\" : \"rskIdn\",  \"mvmSttDat\" : 5,  \"mvmPbl\" : \"mvmPbl\",  \"mvmSucNam\" : \"mvmSucNam\",  \"mvmSttTypNam\" : \"mvmSttTypNam\",  \"plyVal\" : \"plyVal\",  \"rcpVal\" : 5.63737665663332876420099637471139430999755859375,  \"pymOrdVal\" : 2.3021358869347654518833223846741020679473876953125,  \"mvmPrcNam\" : \"mvmPrcNam\",  \"mvmSttTypVal\" : \"mvmSttTypVal\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"mvmTme\" : \"mvmTme\",  \"thrDstHnlNam\" : \"thrDstHnlNam\",  \"mvmPrcIdn\" : \"mvmPrcIdn\",  \"mvmRsnNam\" : \"mvmRsnNam\",  \"mvmIdn\" : \"mvmIdn\",  \"qtnVal\" : \"qtnVal\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
	                } catch (IOException e) {
	                    log.error("Couldn't serialize response for content type application/json", e);
	                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
	                }
	            }
	        } else {
	            log.warn("ObjectMapper or HttpServletRequest not configured in default MovementsRecordApi interface so no example is generated");
	        }
	        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
	    }

}
