/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.cmn.mvd.bo.OCmnMvdS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "movementDefinition", description = "the movementDefinition API")
@RequestMapping(value = "/newtron/api/common")
public interface MovementDefinitionApi {

    Logger log = LoggerFactory.getLogger(MovementDefinitionApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query movement definition", nickname = "getMovementDefinition", notes = "Query movement definition. It will return the defintion of movements. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = OCmnMvdS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Movement Definition", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Movement Record List", response = OCmnMvdS.class, responseContainer = "List") })
    @RequestMapping(value = "/movementDefinition",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OCmnMvdS>> getMovementDefinition(@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Movement Identification", required = true) @Valid @RequestParam(value = "mvmIdn", required = true) List<String> mvmIdn,@ApiParam(value = "Valid date") @Valid @RequestParam(value = "vldDat", required = false) Long vldDat) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"dsbRow\" : \"dsbRow\",  \"nteVal\" : \"nteVal\",  \"mvmPbl\" : \"mvmPbl\",  \"nteClfNam\" : \"nteClfNam\",  \"mvmDsp\" : \"mvmDsp\",  \"cmiTypVal\" : \"cmiTypVal\",  \"mvmTypVal\" : \"mvmTypVal\",  \"vldDat\" : 6,  \"alrCmiHnl\" : \"alrCmiHnl\",  \"cmiTypNam\" : \"cmiTypNam\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"alrCmiHnlNam\" : \"alrCmiHnlNam\",  \"mdfDat\" : 1,  \"nteClfVal\" : \"nteClfVal\",  \"gnrCmq\" : \"gnrCmq\",  \"mvmTypNam\" : \"mvmTypNam\",  \"mvmTrn\" : \"mvmTrn\",  \"usrVal\" : \"usrVal\",  \"mvmIdn\" : \"mvmIdn\"}, {  \"dsbRow\" : \"dsbRow\",  \"nteVal\" : \"nteVal\",  \"mvmPbl\" : \"mvmPbl\",  \"nteClfNam\" : \"nteClfNam\",  \"mvmDsp\" : \"mvmDsp\",  \"cmiTypVal\" : \"cmiTypVal\",  \"mvmTypVal\" : \"mvmTypVal\",  \"vldDat\" : 6,  \"alrCmiHnl\" : \"alrCmiHnl\",  \"cmiTypNam\" : \"cmiTypNam\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"alrCmiHnlNam\" : \"alrCmiHnlNam\",  \"mdfDat\" : 1,  \"nteClfVal\" : \"nteClfVal\",  \"gnrCmq\" : \"gnrCmq\",  \"mvmTypNam\" : \"mvmTypNam\",  \"mvmTrn\" : \"mvmTrn\",  \"usrVal\" : \"usrVal\",  \"mvmIdn\" : \"mvmIdn\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default MovementDefinitionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
