/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.trn.nwo.bo.OTrnNwoS;

import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Optional;

@Api(value = "newtronOperationList", description = "the newtronOperationList API")
@RequestMapping(value = "/newtron/api/common")
public interface NewtronOperationListApi {

    Logger log = LoggerFactory.getLogger(NewtronOperationListApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query Newtron operation", nickname = "getNewtronOperationList", notes = "Query Newtron operations. It will return the newtron operations", response = OTrnNwoS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Newtron Operation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Newtron operation list", response = OTrnNwoS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found.", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/newtronOperationList",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OTrnNwoS>> getNewtronOperationList(@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"oprIdnVal\" : \"oprIdnVal\",  \"oprIdnNam\" : \"oprIdnNam\",  \"lobVal\" : 6.02745618307040320615897144307382404804229736328125,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdfDat\" : 1,  \"molVal\" : \"molVal\",  \"acsUsrVal\" : \"acsUsrVal\",  \"usrVal\" : \"usrVal\",  \"lobNam\" : \"lobNam\"}, {  \"oprIdnVal\" : \"oprIdnVal\",  \"oprIdnNam\" : \"oprIdnNam\",  \"lobVal\" : 6.02745618307040320615897144307382404804229736328125,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdfDat\" : 1,  \"molVal\" : \"molVal\",  \"acsUsrVal\" : \"acsUsrVal\",  \"usrVal\" : \"usrVal\",  \"lobNam\" : \"lobNam\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default NewtronOperationListApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
