/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.tron.api.cmn.model.McaMdtThpNewTrueReponsenDefinition;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "newThirdPartyModel", description = "the newThirdPartyModel API")
@RequestMapping(value = "/newtron/api/common")
public interface NewThirdPartyModelApi {

    Logger log = LoggerFactory.getLogger(NewThirdPartyModelApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query Company New Third Party Model", nickname = "getNewThirdPartyModel", notes = "Query company new third party model. It will return \"S\" if the company is new third party model, otherwise N. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = McaMdtThpNewTrueReponsenDefinition.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "S if the company is new third party model, otherwise N", response = McaMdtThpNewTrueReponsenDefinition.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/newThirdPartyModel",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<McaMdtThpNewTrueReponsenDefinition> getNewThirdPartyModel(@ApiParam(value = "Company code" ,required=true) @RequestHeader(value="cmpVal", required=true) Integer cmpVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"McaMdtThpNew\" : \"McaMdtThpNew\"}", McaMdtThpNewTrueReponsenDefinition.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default NewThirdPartyModelApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
