/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "pid", description = "the pid API")
@RequestMapping(value = "/newtron/api/common")
public interface PidApi {

    Logger log = LoggerFactory.getLogger(PidApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
	return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
	return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
	return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Save daily fund quotation", nickname = "postSaveDailyFundQuotation", notes = "Save daily funds quotation. It will be  mandatory send the parameters defined in the service and the service  will response with the output object defined.", authorizations = {
	    @Authorization(value = "basicAuth") }, tags = { "Life", })
    @ApiResponses(value = { @ApiResponse(code = 201, message = "Operation succesfully done!"),
	    @ApiResponse(code = 400, message = "Bad request", response = Error.class),
	    @ApiResponse(code = 404, message = "Not found", response = Error.class),
	    @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/pid/dfq/lodW/tblPrr", method = RequestMethod.POST)
    default ResponseEntity<Void> postSaveDailyFundQuotation(
	    @ApiParam(value = "User code", required = true) @RequestHeader(value = "usrVal", required = true) String usrVal,
	    @NotNull @ApiParam(value = "Language code", required = true) @Valid @RequestParam(value = "lngVal", required = true) String lngVal,
	    @NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal) {
	if (getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
	} else {
	    log.warn(
		    "ObjectMapper or HttpServletRequest not configured in default PidApi interface so no example is generated");
	}
	return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    @ApiOperation(value = "Save portfolio fund composition", nickname = "postSavePortfolioFundComposition", notes = "Save portfolio fund composition. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", authorizations = {
	    @Authorization(value = "basicAuth") }, tags = { "Life", })
    @ApiResponses(value = { @ApiResponse(code = 201, message = "Operation succesfully done!"),
	    @ApiResponse(code = 400, message = "Bad request", response = Error.class),
	    @ApiResponse(code = 404, message = "Not found", response = Error.class),
	    @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/pid/pfc/lodW/tblPrr", method = RequestMethod.POST)
    default ResponseEntity<Void> postSavePortfolioFundComposition(
	    @ApiParam(value = "User code", required = true) @RequestHeader(value = "usrVal", required = true) String usrVal,
	    @NotNull @ApiParam(value = "Language code", required = true) @Valid @RequestParam(value = "lngVal", required = true) String lngVal,
	    @NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal) {
	if (getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
	} else {
	    log.warn(
		    "ObjectMapper or HttpServletRequest not configured in default PidApi interface so no example is generated");
	}
	return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
