/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.trn.evn.bo.OTrnEvnS;

import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Optional;

@Api(value = "queryEventNotProcessed", description = "the queryEventNotProcessed API")
@RequestMapping(value = "/newtron/api/common")
public interface QueryEventNotProcessedApi {

    Logger log = LoggerFactory.getLogger(QueryEventNotProcessedApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query message list for event not processed", nickname = "getQueryEventNotProcessed", notes = "Query message list for event not processed. It will return the message for event", response = OTrnEvnS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Message event list", response = OTrnEvnS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found.", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/queryEventNotProcessed",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<List<OTrnEvnS>> getQueryEventNotProcessed(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Query Date", required = true) @Valid @RequestParam(value = "qryDat", required = true) Long qryDat,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Event Identifier") @Valid @RequestParam(value = "evnIdnVal", required = false) Integer evnIdnVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"msgVal\" : \"msgVal\",  \"evnIdnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdfDat\" : 5,  \"scnIdnVal\" : 1.46581298050294517310021547018550336360931396484375,  \"evnIdnNam\" : \"evnIdnNam\",  \"usrVal\" : \"usrVal\",  \"rcrPssChc\" : \"rcrPssChc\"}, {  \"msgVal\" : \"msgVal\",  \"evnIdnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdfDat\" : 5,  \"scnIdnVal\" : 1.46581298050294517310021547018550336360931396484375,  \"evnIdnNam\" : \"evnIdnNam\",  \"usrVal\" : \"usrVal\",  \"rcrPssChc\" : \"rcrPssChc\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default QueryEventNotProcessedApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
