/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.lsf.rek.bo.OLsfRekS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "reasonEventlockingDefinition", description = "the reasonEventlockingDefinition API")
@RequestMapping(value = "/newtron/api/common")
public interface ReasonEventlockingDefinitionApi {

	Logger log = LoggerFactory.getLogger(ReasonEventlockingDefinitionApi.class);

	default Optional<ObjectMapper> getObjectMapper() {
		return Optional.empty();
	}

	default Optional<HttpServletRequest> getRequest() {
		return Optional.empty();
	}

	default Optional<String> getAcceptHeader() {
		return getRequest().map(r -> r.getHeader("Accept"));
	}

	@SuppressWarnings("unchecked")
	@ApiOperation(value = "Query Reason event locking definition", nickname = "getReasonEventlockingDefinition", notes = "This service will recieve a code with the value of the reason and will retrieve all the information regarding the reason. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = OLsfRekS.class, responseContainer = "List", authorizations = {
			@Authorization(value = "basicAuth") }, tags = { "Reason event locking definition", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "List of reason event locking definition", response = OLsfRekS.class, responseContainer = "List"),
			@ApiResponse(code = 400, message = "Bad request", response = Error.class),
			@ApiResponse(code = 404, message = "Not found", response = Error.class),
			@ApiResponse(code = 500, message = "Uncontrolled error", response = Error.class) })
	@RequestMapping(value = "/reasonEventlockingDefinition", produces = {
			"application/json" }, method = RequestMethod.GET)
	default ResponseEntity<List<OLsfRekS>> getReasonEventlockingDefinition(
			@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) BigDecimal cmpVal,
			@ApiParam(value = "Language code", required = true) @RequestHeader(value = "lngVal", required = true) String lngVal,
			@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal) {
		if (getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
			if (getAcceptHeader().get().contains("application/json")) {
				try {
					return new ResponseEntity<>(getObjectMapper().get().readValue(
							"[ {  \"rsnLckNam\" : \"rsnLckNam\",  \"adtTxtChc\" : \"adtTxtChc\",  \"dsbRow\" : \"dsbRow\",  \"lngVal\" : \"lngVal\",  \"stsSswNam\" : \"stsSswNam\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdfDat\" : 1,  \"rsnLckVal\" : \"rsnLckVal\",  \"mvmVal\" : 6.02745618307040320615897144307382404804229736328125,  \"stsSswVal\" : \"stsSswVal\",  \"usrVal\" : \"usrVal\"}, {  \"rsnLckNam\" : \"rsnLckNam\",  \"adtTxtChc\" : \"adtTxtChc\",  \"dsbRow\" : \"dsbRow\",  \"lngVal\" : \"lngVal\",  \"stsSswNam\" : \"stsSswNam\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdfDat\" : 1,  \"rsnLckVal\" : \"rsnLckVal\",  \"mvmVal\" : 6.02745618307040320615897144307382404804229736328125,  \"stsSswVal\" : \"stsSswVal\",  \"usrVal\" : \"usrVal\"} ]",
							List.class), HttpStatus.NOT_IMPLEMENTED);
				} catch (IOException e) {
					log.error("Couldn't serialize response for content type application/json", e);
					return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
				}
			}
		} else {
			log.warn(
					"ObjectMapper or HttpServletRequest not configured in default ReasonEventlockingDefinitionApi interface so no example is generated");
		}
		return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
	}

}
