/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.cmu.snl.bo.OCmuSnlS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "secondLevels", description = "the secondLevels API")
@RequestMapping(value = "/newtron/api/common")
public interface SecondLevelsApi {

    Logger log = LoggerFactory.getLogger(SecondLevelsApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query Second Level List", nickname = "getSecondLevels", notes = "Query the second level list. It will return the list of second levels of the commercial structure . It will be mandatory send  the parameters defined in the service and the service will response with the output object defined.", response = OCmuSnlS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Second Level List", response = OCmuSnlS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/secondLevels",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OCmuSnlS>> getSecondLevels(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@NotNull @ApiParam(value = "First Level", required = true) @Valid @RequestParam(value = "frsLvlVal", required = true) BigDecimal frsLvlVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"dsbRow\" : \"dsbRow\",  \"frsLvlNam\" : \"frsLvlNam\",  \"isuCmu\" : \"isuCmu\",  \"scnLvlNam\" : \"scnLvlNam\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"cmuScnLvlObsVal\" : \"cmuScnLvlObsVal\",  \"scnLvlVal\" : 1.46581298050294517310021547018550336360931396484375,  \"frsLvlVal\" : 6.02745618307040320615897144307382404804229736328125,  \"scnCmuAbr\" : \"scnCmuAbr\"}, {  \"dsbRow\" : \"dsbRow\",  \"frsLvlNam\" : \"frsLvlNam\",  \"isuCmu\" : \"isuCmu\",  \"scnLvlNam\" : \"scnLvlNam\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"cmuScnLvlObsVal\" : \"cmuScnLvlObsVal\",  \"scnLvlVal\" : 1.46581298050294517310021547018550336360931396484375,  \"frsLvlVal\" : 6.02745618307040320615897144307382404804229736328125,  \"scnCmuAbr\" : \"scnCmuAbr\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default SecondLevelsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
