/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.cmn.ssg.bo.OCmnSsgS;

import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Optional;

@Api(value = "storageFromSelfService", description = "the storageFromSelfService API")
@RequestMapping(value = "/newtron/api/common")
public interface StorageFromSelfServiceApi {

    Logger log = LoggerFactory.getLogger(StorageFromSelfServiceApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Create Storage From Self-Service", nickname = "postStorageFromSelfService", notes = "Create Storage From SelfService. It will create new variables from the self service front end. It will be mandatory send the parameters  defined in the service and the service will response with the output  object defined.", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Self-Service", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Operation succesfully done!"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/storageFromSelfService",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<Void> postStorageFromSelfService(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@ApiParam(value = "Input data to new self service storage" ,required=true )  @Valid @RequestBody List<OCmnSsgS> inSelfServiceStorage) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default StorageFromSelfServiceApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
    
    @ApiOperation(value = "Query Storage From Self-Service", nickname = "getStorageFromSelfService", notes = "Query Storage From SelfService. It will return the variables saved for the self service front end. It will be mandatory send the parameters  defined in the service and the service will response with the output  object defined.", response = OCmnSsgS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Self-Service", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Self-Service Storage", response = OCmnSsgS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/storageFromSelfService",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OCmnSsgS>> getStorageFromSelfService(@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Self-Service Section", required = true) @Valid @RequestParam(value = "sfrSciVal", required = true) String sfrSciVal,@NotNull @ApiParam(value = "Self-Service Subsection", required = true) @Valid @RequestParam(value = "sfrSbsVal", required = true) String sfrSbsVal,@ApiParam(value = "Authentication Identifier") @Valid @RequestParam(value = "sfrIdnVal", required = false) List<String> sfrIdnVal,@ApiParam(value = "Variable Description") @Valid @RequestParam(value = "vrbDspVal", required = false) String vrbDspVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"vrbDspVal\" : \"vrbDspVal\",  \"dsbRow\" : \"dsbRow\",  \"sfrSbsVal\" : \"sfrSbsVal\",  \"sfrSciVal\" : \"sfrSciVal\",  \"vldDat\" : 6,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdfDat\" : 1,  \"sfrSqnVal\" : \"sfrSqnVal\",  \"vrbVal\" : \"vrbVal\",  \"usrVal\" : \"usrVal\",  \"sfrIdnVal\" : \"sfrIdnVal\"}, {  \"vrbDspVal\" : \"vrbDspVal\",  \"dsbRow\" : \"dsbRow\",  \"sfrSbsVal\" : \"sfrSbsVal\",  \"sfrSciVal\" : \"sfrSciVal\",  \"vldDat\" : 6,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdfDat\" : 1,  \"sfrSqnVal\" : \"sfrSqnVal\",  \"vrbVal\" : \"vrbVal\",  \"usrVal\" : \"usrVal\",  \"sfrIdnVal\" : \"sfrIdnVal\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default StorageFromSelfServiceApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
