/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.cmu.thl.bo.OCmuThlS;
import com.mapfre.nwt.trn.thp.adr.bo.OThpAdrS;
import com.mapfre.nwt.trn.thp.cnt.bo.OThpCntS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "thirdLevel", description = "the thirdLevel API")
@RequestMapping(value = "/newtron/api/common")
public interface ThirdLevelApi {

    Logger log = LoggerFactory.getLogger(ThirdLevelApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query Third Level", nickname = "getThirdLevel", notes = "Query the third level. It will return the third level of the commercial structure . It will be mandatory send  the parameters defined in the service and the service will response with the output object defined.", response = OCmuThlS.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Third Level", response = OCmuThlS.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/thirdLevel/{thrLvlVal}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<OCmuThlS> getThirdLevel(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Third Level",required=true) @PathVariable("thrLvlVal") Integer thrLvlVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"dsbRow\" : \"dsbRow\",  \"rcoThrLvlVal\" : 5.63737665663332876420099637471139430999755859375,  \"rvrRcy\" : \"rvrRcy\",  \"frsLvlNam\" : \"frsLvlNam\",  \"cmuThrLvlObsVal\" : \"cmuThrLvlObsVal\",  \"thrCmuAbr\" : \"thrCmuAbr\",  \"secVal\" : 7.061401241503109105224211816675961017608642578125,  \"slvRcy\" : \"slvRcy\",  \"balDstTypVal\" : 0.80082819046101150206595775671303272247314453125,  \"mtlPcs\" : \"mtlPcs\",  \"thrLvlOwnCmu\" : \"thrLvlOwnCmu\",  \"plsPcs\" : \"plsPcs\",  \"trlFil\" : \"trlFil\",  \"thrLvlNam\" : \"thrLvlNam\",  \"opgDat\" : 5,  \"isuCmu\" : \"isuCmu\",  \"scnLvlNam\" : \"scnLvlNam\",  \"totLss\" : \"totLss\",  \"cmpVal\" : 6.02745618307040320615897144307382404804229736328125,  \"thrLvlVal\" : 9.301444243932575517419536481611430644989013671875,  \"scnLvlVal\" : 2.3021358869347654518833223846741020679473876953125,  \"frsLvlVal\" : 1.46581298050294517310021547018550336360931396484375,  \"rco\" : \"rco\"}", OCmuThlS.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ThirdLevelApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
    
    @ApiOperation(value = "Query Contact From Third Level", nickname = "getContactFromThirdLevel", notes = "Query the third level contact information. It will return the contact of the third level of the commercial structure . It will be mandatory send  the parameters defined in the service and the service will response with the output object defined.", response = OThpCntS.class, authorizations = {
	        @Authorization(value = "basicAuth")
	    }, tags={ "Common", })
	    @ApiResponses(value = { 
	        @ApiResponse(code = 200, message = "Contact Information", response = OThpCntS.class),
	        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
	        @ApiResponse(code = 404, message = "Not found", response = Error.class),
	        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
	    @RequestMapping(value = "/thirdLevel/{thrLvlVal}/contact",
	        produces = { "application/json" }, 
	        method = RequestMethod.GET)
	    default ResponseEntity<OThpCntS> getContactFromThirdLevel(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Third Level",required=true) @PathVariable("thrLvlVal") Integer thrLvlVal) {
	        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
	            if (getAcceptHeader().get().contains("application/json")) {
	                try {
	                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"emlAdr\" : \"emlAdr\",  \"tlpCnyCck\" : \"tlpCnyCck\",  \"thpAcvVal\" : 2.3021358869347654518833223846741020679473876953125,  \"clrTlpCck\" : \"clrTlpCck\",  \"cntPrsNtnVal\" : \"cntPrsNtnVal\",  \"bprVal\" : \"bprVal\",  \"mdfScoVal\" : \"mdfScoVal\",  \"cntPrsNtnTypNam\" : \"cntPrsNtnTypNam\",  \"cntPrsSrn\" : \"cntPrsSrn\",  \"tlpVal\" : \"tlpVal\",  \"areClrTlpVal\" : \"areClrTlpVal\",  \"tlpExtVal\" : \"tlpExtVal\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"mdfDat\" : 1,  \"faxVal\" : \"faxVal\",  \"pstTypVal\" : \"pstTypVal\",  \"sqnVal\" : 5.63737665663332876420099637471139430999755859375,  \"thpVal\" : 7.061401241503109105224211816675961017608642578125,  \"bprCck\" : \"bprCck\",  \"cnyClrTlpVal\" : \"cnyClrTlpVal\",  \"pstTypNam\" : \"pstTypNam\",  \"tlpAreVal\" : \"tlpAreVal\",  \"cntTypVal\" : \"cntTypVal\",  \"ecmAcvTypNam\" : \"ecmAcvTypNam\",  \"emlAdrCck\" : \"emlAdrCck\",  \"cntTypNam\" : \"cntTypNam\",  \"thpDcmVal\" : \"thpDcmVal\",  \"clrTlpVal\" : \"clrTlpVal\",  \"plyVal\" : \"plyVal\",  \"thpDcmTypVal\" : \"thpDcmTypVal\",  \"ecmAcvTypVal\" : \"ecmAcvTypVal\",  \"faxCck\" : \"faxCck\",  \"vldDat\" : 9,  \"cntPrsNam\" : \"cntPrsNam\",  \"rskVal\" : 5.962133916683182377482808078639209270477294921875,  \"enrSqn\" : 6.02745618307040320615897144307382404804229736328125,  \"acnOrgVal\" : \"acnOrgVal\",  \"tlpCnyVal\" : \"tlpCnyVal\"}", OThpCntS.class), HttpStatus.NOT_IMPLEMENTED);
	                } catch (IOException e) {
	                    log.error("Couldn't serialize response for content type application/json", e);
	                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
	                }
	            }
	        } else {
	            log.warn("ObjectMapper or HttpServletRequest not configured in default ThirdLevelApi interface so no example is generated");
	        }
	        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
	    }


        @ApiOperation(value = "Query Address From Third Level", nickname = "getAddresstFromThirdLevel", notes = "Query the third level address information. It will return the address of the third level of the commercial structure . It will be mandatory send  the parameters defined in the service and the service will response with the output object defined.", response = OThpAdrS.class, authorizations = {
            @Authorization(value = "basicAuth")
        }, tags={ "Common", })
        @ApiResponses(value = { 
            @ApiResponse(code = 200, message = "Address Information", response = OThpAdrS.class),
            @ApiResponse(code = 400, message = "Bad request", response = Error.class),
            @ApiResponse(code = 404, message = "Not found", response = Error.class),
            @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
        @RequestMapping(value = "/thirdLevel/{thrLvlVal}/address",
            produces = { "application/json" }, 
            method = RequestMethod.GET)
        default ResponseEntity<OThpAdrS> getAddresstFromThirdLevel(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Third Level",required=true) @PathVariable("thrLvlVal") Integer thrLvlVal) {
            if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
                if (getAcceptHeader().get().contains("application/json")) {
                    try {
                        return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"adrTypNam\" : \"adrTypNam\",  \"lntVal\" : \"lntVal\",  \"dmlTypNam\" : \"dmlTypNam\",  \"thpAcvVal\" : 7.061401241503109105224211816675961017608642578125,  \"dmlTypVal\" : \"dmlTypVal\",  \"lblTypVal\" : \"lblTypVal\",  \"mdfScoVal\" : \"mdfScoVal\",  \"scnAdrLinNam\" : \"scnAdrLinNam\",  \"pvcVal\" : 5.962133916683182377482808078639209270477294921875,  \"frsAdrLinNam\" : \"frsAdrLinNam\",  \"cmlCmpNam\" : \"cmlCmpNam\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"fthAdrLinNam\" : \"fthAdrLinNam\",  \"mdfDat\" : 1,  \"thrAdrLinNam\" : \"thrAdrLinNam\",  \"thpVal\" : 9.301444243932575517419536481611430644989013671875,  \"adrStrVal\" : \"adrStrVal\",  \"adrCck\" : \"adrCck\",  \"adrFlrVal\" : \"adrFlrVal\",  \"twnVal\" : 3.61607674925191080461672754609026014804840087890625,  \"cnyVal\" : \"cnyVal\",  \"lblNam\" : \"lblNam\",  \"adrIdsVal\" : \"adrIdsVal\",  \"pslCodVal\" : \"pslCodVal\",  \"thpDcmVal\" : \"thpDcmVal\",  \"adrStaVal\" : \"adrStaVal\",  \"plyVal\" : \"plyVal\",  \"adrDorVal\" : \"adrDorVal\",  \"thpDcmTypVal\" : \"thpDcmTypVal\",  \"lttVal\" : \"lttVal\",  \"sttNam\" : \"sttNam\",  \"vrnTwnNam\" : \"vrnTwnNam\",  \"pslCodExtVal\" : \"pslCodExtVal\",  \"vldDat\" : 2,  \"adrDrwVal\" : \"adrDrwVal\",  \"pobVal\" : \"pobVal\",  \"pvcNam\" : \"pvcNam\",  \"rskVal\" : 5.63737665663332876420099637471139430999755859375,  \"cnyNam\" : \"cnyNam\",  \"adrTypVal\" : \"adrTypVal\",  \"enrSqn\" : 6.02745618307040320615897144307382404804229736328125,  \"sttVal\" : 2.3021358869347654518833223846741020679473876953125,  \"acnOrgVal\" : \"acnOrgVal\",  \"frtAdrLinNam\" : \"frtAdrLinNam\",  \"twnNam\" : \"twnNam\",  \"vrnTwnVal\" : 4.1456080298839363962315474054776132106781005859375}", OThpAdrS.class), HttpStatus.NOT_IMPLEMENTED);
                    } catch (IOException e) {
                        log.error("Couldn't serialize response for content type application/json", e);
                        return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                    }
                }
            } else {
                log.warn("ObjectMapper or HttpServletRequest not configured in default ThirdLevelApi interface so no example is generated");
            }
            return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
        }


        @ApiOperation(value = "Query Contact From Third Level", nickname = "getContactFromThirdLevelv1", notes = "Query the third level contact information. It will return the contact of the third level of the commercial structure . It will be mandatory send  the parameters defined in the service and the service will response with the output object defined.", response = OThpCntS.class, responseContainer = "List", authorizations = {
            @Authorization(value = "basicAuth")
        }, tags={ "Common", })
        @ApiResponses(value = { 
            @ApiResponse(code = 200, message = "Contact Information", response = OThpCntS.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "Bad request", response = Error.class),
            @ApiResponse(code = 404, message = "Not found", response = Error.class),
            @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
        @RequestMapping(value = "/thirdLevel/1.0/{thrLvlVal}/contact",
            produces = { "application/json" }, 
            method = RequestMethod.GET)
        default ResponseEntity<List<OThpCntS>> getContactFromThirdLevelv1(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Third Level",required=true) @PathVariable("thrLvlVal") Integer thrLvlVal) {
            if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
                if (getAcceptHeader().get().contains("application/json")) {
                    try {
                        return new ResponseEntity<>(getObjectMapper().get().readValue("", List.class), HttpStatus.NOT_IMPLEMENTED);
                    } catch (IOException e) {
                        log.error("Couldn't serialize response for content type application/json", e);
                        return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                    }
                }
            } else {
                log.warn("ObjectMapper or HttpServletRequest not configured in default ThirdLevelApi interface so no example is generated");
            }
            return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
        }

        @ApiOperation(value = "Query Address From Third Level 1", nickname = "getAddresstFromThirdLevelv1", notes = "Query the third level address information. It will return the address of the third level of the commercial structure . It will be mandatory send  the parameters defined in the service and the service will response with the output object defined.", response = OThpAdrS.class, responseContainer = "List", authorizations = {
            @Authorization(value = "basicAuth")
        }, tags={ "Common", })
        @ApiResponses(value = { 
            @ApiResponse(code = 200, message = "Address Information", response = OThpAdrS.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "Bad request", response = Error.class),
            @ApiResponse(code = 404, message = "Not found", response = Error.class),
            @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
        @RequestMapping(value = "/thirdLevel/1.0/{thrLvlVal}/address",
            produces = { "application/json" }, 
            method = RequestMethod.GET)
        default ResponseEntity<List<OThpAdrS>> getAddresstFromThirdLevelv1(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Third Level",required=true) @PathVariable("thrLvlVal") Integer thrLvlVal) {
            if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
                if (getAcceptHeader().get().contains("application/json")) {
                    try {
                        return new ResponseEntity<>(getObjectMapper().get().readValue("", List.class), HttpStatus.NOT_IMPLEMENTED);
                    } catch (IOException e) {
                        log.error("Couldn't serialize response for content type application/json", e);
                        return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                    }
                }
            } else {
                log.warn("ObjectMapper or HttpServletRequest not configured in default ThirdLevelApi interface so no example is generated");
            }
            return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
        }


}
