/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.trn.vrb.bo.OTrnVrbS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "variableDefinition", description = "the variableDefinition API")
@RequestMapping(value = "/newtron/api/common")
public interface VariableDefinitionApi {

    Logger log = LoggerFactory.getLogger(VariableDefinitionApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query variable definition by company", nickname = "getVariableDefinitionByCompany", notes = "Query variable  definition by company. It will return the variable definition filtering by company", response = OTrnVrbS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Variable Definition", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Variable Definition List", response = OTrnVrbS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found.", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/variableDefinition/queryByCompany",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OTrnVrbS>> getVariableDefinitionByCompany(@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Variable Name", required = true) @Valid @RequestParam(value = "vrbNamVal", required = true) String vrbNamVal,@ApiParam(value = "Validation Date") @Valid @RequestParam(value = "vldDat", required = false) Long vldDat) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"vrbDspVal\" : \"vrbDspVal\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 1,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"vrbVal\" : \"vrbVal\",  \"adtVal\" : \"adtVal\",  \"prnVrbVal\" : \"prnVrbVal\",  \"dflValPem\" : \"dflValPem\"}, {  \"vrbDspVal\" : \"vrbDspVal\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 1,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"vrbVal\" : \"vrbVal\",  \"adtVal\" : \"adtVal\",  \"prnVrbVal\" : \"prnVrbVal\",  \"dflValPem\" : \"dflValPem\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default VariableDefinitionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Query a variable definition by company", nickname = "getVariableDefinitionByCompanyById", notes = "Query variable  definition by company. It will return the variable definition filtering by company", response = OTrnVrbS.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Variable Definition", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Variable Definition", response = OTrnVrbS.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found.", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/variableDefinition/queryByCompany/{vrbVal}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<OTrnVrbS> getVariableDefinitionByCompanyById(@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Variable Name", required = true) @Valid @RequestParam(value = "vrbNamVal", required = true) String vrbNamVal,@ApiParam(value = "Variable Value",required=true) @PathVariable("vrbVal") String vrbVal,@ApiParam(value = "Validation Date") @Valid @RequestParam(value = "vldDat", required = false) Long vldDat) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"vrbDspVal\" : \"vrbDspVal\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 1,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"vrbVal\" : \"vrbVal\",  \"adtVal\" : \"adtVal\",  \"prnVrbVal\" : \"prnVrbVal\",  \"dflValPem\" : \"dflValPem\"}", OTrnVrbS.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default VariableDefinitionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Query variable definition by coverage", nickname = "getVariableDefinitionByCoverage", notes = "Query variable  definition by coverage. It will return the variable definition filtering by coverage", response = OTrnVrbS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Variable Definition", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Variable Definition List", response = OTrnVrbS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found.", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/variableDefinition/queryByCoverage",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OTrnVrbS>> getVariableDefinitionByCoverage(@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Line of Business", required = true) @Valid @RequestParam(value = "lobVal", required = true) Integer lobVal,@NotNull @ApiParam(value = "Coverage", required = true) @Valid @RequestParam(value = "cvrVal", required = true) Integer cvrVal,@NotNull @ApiParam(value = "Variable Name", required = true) @Valid @RequestParam(value = "vrbNamVal", required = true) String vrbNamVal,@ApiParam(value = "Modality") @Valid @RequestParam(value = "mdtVal", required = false) Integer mdtVal,@ApiParam(value = "Validation Date") @Valid @RequestParam(value = "vldDat", required = false) Long vldDat,@ApiParam(value = "Parent Variable Value") @Valid @RequestParam(value = "prnVrbVal", required = false) String prnVrbVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"vrbDspVal\" : \"vrbDspVal\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 1,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"vrbVal\" : \"vrbVal\",  \"adtVal\" : \"adtVal\",  \"prnVrbVal\" : \"prnVrbVal\",  \"dflValPem\" : \"dflValPem\"}, {  \"vrbDspVal\" : \"vrbDspVal\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 1,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"vrbVal\" : \"vrbVal\",  \"adtVal\" : \"adtVal\",  \"prnVrbVal\" : \"prnVrbVal\",  \"dflValPem\" : \"dflValPem\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default VariableDefinitionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Query variable definition by line of business", nickname = "getVariableDefinitionByLineOfBusiness", notes = "Query variable  definition by line of business. It will return the variable definition filtering by company and line of business", response = OTrnVrbS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Variable Definition", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Variable Definition List", response = OTrnVrbS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found.", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/variableDefinition/queryByLineOfBusiness",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OTrnVrbS>> getVariableDefinitionByLineOfBusiness(@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Line of Business", required = true) @Valid @RequestParam(value = "lobVal", required = true) Integer lobVal,@NotNull @ApiParam(value = "Variable Name", required = true) @Valid @RequestParam(value = "vrbNamVal", required = true) String vrbNamVal,@ApiParam(value = "Validation Date") @Valid @RequestParam(value = "vldDat", required = false) Long vldDat) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"vrbDspVal\" : \"vrbDspVal\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 1,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"vrbVal\" : \"vrbVal\",  \"adtVal\" : \"adtVal\",  \"prnVrbVal\" : \"prnVrbVal\",  \"dflValPem\" : \"dflValPem\"}, {  \"vrbDspVal\" : \"vrbDspVal\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 1,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"vrbVal\" : \"vrbVal\",  \"adtVal\" : \"adtVal\",  \"prnVrbVal\" : \"prnVrbVal\",  \"dflValPem\" : \"dflValPem\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default VariableDefinitionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Query variable definition by thrid party", nickname = "getVariableDefinitionByThirdParty", notes = "Query variable  definition by thrid party. It will return the variable definition filtering by third party", response = OTrnVrbS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Variable Definition", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Variable Definition List", response = OTrnVrbS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found.", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/variableDefinition/queryByThirdParty",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OTrnVrbS>> getVariableDefinitionByThirdParty(@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Document type", required = true) @Valid @RequestParam(value = "thpDcmTypVal", required = true) String thpDcmTypVal,@NotNull @ApiParam(value = "Document", required = true) @Valid @RequestParam(value = "thpDcmVal", required = true) String thpDcmVal,@NotNull @ApiParam(value = "Activity", required = true) @Valid @RequestParam(value = "thpAcvVal", required = true) Integer thpAcvVal,@NotNull @ApiParam(value = "Variable Name", required = true) @Valid @RequestParam(value = "vrbNamVal", required = true) String vrbNamVal,@ApiParam(value = "Validation Date") @Valid @RequestParam(value = "vldDat", required = false) Long vldDat) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"vrbDspVal\" : \"vrbDspVal\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 1,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"vrbVal\" : \"vrbVal\",  \"adtVal\" : \"adtVal\",  \"prnVrbVal\" : \"prnVrbVal\",  \"dflValPem\" : \"dflValPem\"}, {  \"vrbDspVal\" : \"vrbDspVal\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 1,  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"sqnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"vrbVal\" : \"vrbVal\",  \"adtVal\" : \"adtVal\",  \"prnVrbVal\" : \"prnVrbVal\",  \"dflValPem\" : \"dflValPem\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default VariableDefinitionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Update variable definition by thrid party", nickname = "putVariableDefinitionByThirdParty", notes = "Update variable  definition by thrid party. It will update the variable definition  by third party", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Variable Definition", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Operation succesfully done!"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found.", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/variableDefinition/upddateByThirdParty",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    default ResponseEntity<Void> putVariableDefinitionByThirdParty(@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Document type", required = true) @Valid @RequestParam(value = "thpDcmTypVal", required = true) String thpDcmTypVal,@NotNull @ApiParam(value = "document", required = true) @Valid @RequestParam(value = "thpDcmVal", required = true) String thpDcmVal,@NotNull @ApiParam(value = "Activity", required = true) @Valid @RequestParam(value = "thpAcvVal", required = true) Integer thpAcvVal,@NotNull @ApiParam(value = "Variable Name", required = true) @Valid @RequestParam(value = "vrbNamVal", required = true) String vrbNamVal,@ApiParam(value = "Input data to update the variable definition" ,required=true )  @Valid @RequestBody OTrnVrbS inVariableDefinition,@ApiParam(value = "Language code") @Valid @RequestParam(value = "lngVal", required = false) String lngVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default VariableDefinitionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
