/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.grs.znf.bo.OGrsZnfS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "zoneFourSubcodeList", description = "the zoneFourSubcodeList API")
@RequestMapping(value = "/newtron/api/common")
public interface ZoneFourSubcodeListApi {

    Logger log = LoggerFactory.getLogger(ZoneFourSubcodeListApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query Zone Four Subcode List", nickname = "getZoneFourSubcodeList", notes = "Query zone four subcode list. It will return the list of zone four subcode list (Districts). It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = OGrsZnfS.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Zone four List", response = OGrsZnfS.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/zoneFourSubcodeList",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<OGrsZnfS>> getZoneFourSubcodeList(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@NotNull @ApiParam(value = "Country", required = true) @Valid @RequestParam(value = "cnyVal", required = true) String cnyVal,@NotNull @ApiParam(value = "State Value", required = true) @Valid @RequestParam(value = "sttVal", required = true) String sttVal,@NotNull @ApiParam(value = "Province Value", required = true) @Valid @RequestParam(value = "pvcVal", required = true) Integer pvcVal,@NotNull @ApiParam(value = "Town Value", required = true) @Valid @RequestParam(value = "twnVal", required = true) Integer twnVal,@ApiParam(value = "real District") @Valid @RequestParam(value = "reaGrsDit", required = false) String reaGrsDit) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"dsbRow\" : \"dsbRow\",  \"twnVal\" : 0.80082819046101150206595775671303272247314453125,  \"cnyVal\" : \"cnyVal\",  \"grsFrtLvl\" : \"grsFrtLvl\",  \"ditNam\" : \"ditNam\",  \"pvcVal\" : 6.02745618307040320615897144307382404804229736328125,  \"ditVal\" : \"ditVal\",  \"sttNam\" : \"sttNam\",  \"twnAbr\" : \"twnAbr\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 5,  \"pvcNam\" : \"pvcNam\",  \"mdfDat\" : 5,  \"cnyNam\" : \"cnyNam\",  \"sttVal\" : 1.46581298050294517310021547018550336360931396484375,  \"twnNam\" : \"twnNam\",  \"vrnNam\" : \"vrnNam\",  \"usrVal\" : \"usrVal\"}, {  \"dsbRow\" : \"dsbRow\",  \"twnVal\" : 0.80082819046101150206595775671303272247314453125,  \"cnyVal\" : \"cnyVal\",  \"grsFrtLvl\" : \"grsFrtLvl\",  \"ditNam\" : \"ditNam\",  \"pvcVal\" : 6.02745618307040320615897144307382404804229736328125,  \"ditVal\" : \"ditVal\",  \"sttNam\" : \"sttNam\",  \"twnAbr\" : \"twnAbr\",  \"lngVal\" : \"lngVal\",  \"vldDat\" : 5,  \"pvcNam\" : \"pvcNam\",  \"mdfDat\" : 5,  \"cnyNam\" : \"cnyNam\",  \"sttVal\" : 1.46581298050294517310021547018550336360931396484375,  \"twnNam\" : \"twnNam\",  \"vrnNam\" : \"vrnNam\",  \"usrVal\" : \"usrVal\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ZoneFourSubcodeListApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
