/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.io.IOException;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.nwt.trn.grs.znf.bo.OGrsZnfS;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "zoneFour", description = "the zoneFour API")
@RequestMapping(value = "/newtron/api/common")
public interface ZoneFourApi {

    Logger log = LoggerFactory.getLogger(ZoneFourApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Query Zone Four", nickname = "getZoneFour", notes = "Query zone four. It will return the information of a zone four. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = OGrsZnfS.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Zone four", response = OGrsZnfS.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal error", response = Error.class) })
    @RequestMapping(value = "/zoneFour",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<OGrsZnfS> getZoneFour(@ApiParam(value = "Company code" ,required=true) @RequestHeader(value="cmpVal", required=true) Integer cmpVal,@ApiParam(value = "User code" ,required=true) @RequestHeader(value="usrVal", required=true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@ApiParam(value = "Country" ,required=true) @RequestHeader(value="cnyVal", required=true) String cnyVal,@ApiParam(value = "Province Value" ,required=true) @RequestHeader(value="pvcVal", required=true) Integer pvcVal,@ApiParam(value = "Town Value" ,required=true) @RequestHeader(value="twnVal", required=true) Integer twnVal) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"dsbRow\" : \"dsbRow\",  \"twnAbr\" : \"twnAbr\",  \"twnVal\" : 6.02745618307040320615897144307382404804229736328125,  \"cnyVal\" : \"cnyVal\",  \"pvcNam\" : \"pvcNam\",  \"grsFrtLvl\" : \"grsFrtLvl\",  \"cnyNam\" : \"cnyNam\",  \"twnNam\" : \"twnNam\",  \"vrnNam\" : \"vrnNam\",  \"pvcVal\" : 0.80082819046101150206595775671303272247314453125}", OGrsZnfS.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ZoneFourApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
