#
# This file is used to define properties that change in different deployable environments.
#

# This property defines the active Spring profile.
#
app.env.spring.active.profile=${app.env.spring.active.profile}
#
# This property defines the active Spring profile access (Newtron / Tronweb).
#
app.env.spring.active.profile.user=${app.env.spring.active.profile.user}
#
# This property defines the server where the application is going to be deployed.
# It is used to obtain the data base connection.
#
app.env.server.type=${app.env.server.type}
#
# This property set if GaiaRestExceptionHandler is enabled, for handler exception and transform to GaiaSoaException
#
gaia.env.rest.exceptionHanlder.enabled=${gaia.env.rest.exceptionHanlder.enabled}
#
# This property defines the number of StackTrace that are shown in a GaiaSoaExceptionInfo
#
app.env.soa.error.max-stack-trace-elements=${app.env.soa.error.max-stack-trace-elements}
#
#This property defines the application name that is shown in GaiaSoaExceptionInfo
#
app.env.name=${app.env.name}
#
#These properties define the connection data for DB access
#
# newtron datasource
app.env.nwt.datasource.ref.jndi=${app.env.nwt.datasource.ref.jndi}
app.env.nwt.datasource.url=${app.env.nwt.datasource.url}
app.env.nwt.datasource.u=${app.env.nwt.datasource.u}
app.env.nwt.datasource.p=${app.env.nwt.datasource.p}
# tronweb data logic datasource
app.env.tw.dl.datasource.ref.jndi=${app.env.tw.dl.datasource.ref.jndi}
app.env.tw.dl.datasource.url=${app.env.tw.dl.datasource.url}
app.env.tw.dl.datasource.u=${app.env.tw.dl.datasource.u}
app.env.tw.dl.datasource.p=${app.env.tw.dl.datasource.p}
# tronweb procedure datasource
app.env.tw.pr.datasource.ref.jndi=${app.env.tw.pr.datasource.ref.jndi}
app.env.tw.pr.datasource.url=${app.env.tw.pr.datasource.url}
app.env.tw.pr.datasource.u=${app.env.tw.pr.datasource.u}
app.env.tw.pr.datasource.p=${app.env.tw.pr.datasource.p}


app.mail.host=${app.mail.host}
app.mail.port=${app.mail.port}
app.mail.username=${app.mail.username}
app.mail.password=${app.mail.password}

app.sms.username=${app.sms.username}
app.sms.password=${app.sms.password}

app.env.security.authorization=true


#
# This property defines the endpoint for the report service
#
app.env.report.endpoint=${app.env.report.endpoint}

#
# This properties define application info properties
#
app.system.info.project.version=${app.system.info.project.version}
app.system.info.be.version.dependency=${app.system.info.be.version.dependency}

## Configuring actuator info endpoint
info.app.name=nwt_cmn_api_be
info.app.version=${app.system.info.project.version}
info.app.description=Common API
info.app.details.dependencies.beVersion=${app.system.info.be.version.dependency}

# psypd connection data
app.env.psypd.timeout=${app.env.psypd.timeout}
app.env.psypd.basePath=${app.env.psypd.basePath}
app.env.psypd.clientId=${app.env.psypd.clientId}
app.env.psypd.clientSecret=${app.env.psypd.clientSecret}
app.env.psypd.scope=${app.env.psypd.scope}
app.env.psypd.tokenPath=${app.env.psypd.tokenPath}

#BE external services 
app.env.infovl.url=${app.env.infovl.url}
app.env.infovl.username=${app.env.infovl.username}
app.env.infovl.password=${app.env.infovl.password}


app.env.infocestas.url=${app.env.infocestas.url}
app.env.infocestas.username=${app.env.infocestas.username}
app.env.infocestas.password=${app.env.infocestas.password}

#variables
default.app.language=${default.app.language}
default.app.cmpVal=${default.app.cmpVal}

app.env.urlSFMCtoken=${app.env.urlSFMCtoken}
app.env.clientIdSFMCtoken=${app.env.clientIdSFMCtoken}
app.env.clientSecretSFMCtoken=${app.env.clientSecretSFMCtoken}
app.env.urlSFMCevent=${app.env.urlSFMCevent}
app.env.usernameSFTPSFM=${app.env.usernameSFTPSFM}
app.env.passwordSFTPSFM=${app.env.passwordSFTPSFM}
app.env.remoteHostSFTPSCM=${app.env.remoteHostSFTPSCM}
app.env.mvmIdnCommunication=${app.env.mvmIdnCommunication}
app.env.realEnvironment=${app.env.realEnvironment}

# The proxy sock config
app.env.proxy.socksProxyHost=${app.env.proxy.socksProxyHost}
app.env.proxy.socksProxyPort=${app.env.proxy.socksProxyPort}
app.env.proxy.username=${app.env.proxy.username}
app.env.proxy.password=${app.env.proxy.password}

# Peca log file
app.env.peca.filename=${app.env.peca.filename}

# TranslatorThirdPartyModel Properties
app.env.AdrTranslator.home=${app.env.AdrTranslator.home}
app.env.AdrTranslator.office=${app.env.AdrTranslator.office}
app.env.AdrTranslator.correspondence=${app.env.AdrTranslator.correspondence}
app.env.AdrTranslator.defaultAddressCorrespondence=${app.env.AdrTranslator.defaultAddressCorrespondence}
app.env.CntTranslator.home=${app.env.CntTranslator.home}
app.env.CntTranslator.office=${app.env.CntTranslator.office}
app.env.CntTranslator.correspondence=${app.env.CntTranslator.correspondence}
app.env.AdrTranslator.defaultAdr=${app.env.AdrTranslator.defaultAdr}
app.env.CntTranslator.defaultCnt=${app.env.CntTranslator.defaultCnt}
app.env.CntTranslator.priorityCnt=${app.env.CntTranslator.priorityCnt}

# Cache eviction configuration (cron format)
cache.clean.cron.expression=${cache.clean.cron.expression}

#Nueva config

app.env.plinvoker.base-package=com.mapfre.nwt.trn
app.env.plinvoker.object-prefix=NWT_O.
app.env.plinvoker.enable-context-info=false

# required to overwrite mvc autoconfiguration bean

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# actuator
management.endpoints.web.exposure.include=*
#swagger
prop.swagger.enabled=true

# LdapHealthIndicator
management.health.ldap.enabled=false
# MailHealthIndicator
management.health.mail.enabled=false

server.servlet.context-path=${app.url.contextroot}

spring.datasource.nwt.connection-timeout=20000
spring.datasource.nwt.minimum-idle= 10
spring.datasource.nwt.maximum-pool-size= 10
spring.datasource.nwt.idle-timeout=10000
spring.datasource.nwt.max-lifetime= 1000
spring.datasource.nwt.auto-commit=true
spring.datasource.nwt.jdbc-url=${app.env.nwt.datasource.url}
spring.datasource.nwt.username=${app.env.nwt.datasource.u}
spring.datasource.nwt.password=${app.env.nwt.datasource.p}
spring.datasource.nwt.pool-name=nwt-pool-cmn
spring.datasource.nwt.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.nwt.type=com.zaxxer.hikari.HikariDataSource


spring.datasource.twdl.connection-timeout=20000
spring.datasource.twdl.minimum-idle=10
spring.datasource.twdl.maximum-pool-size=10
spring.datasource.twdl.idle-timeout=10000
spring.datasource.twdl.max-lifetime=1000
spring.datasource.twdl.auto-commit=true
spring.datasource.twdl.jdbc-url=${app.env.tw.dl.datasource.url}
spring.datasource.twdl.username=${app.env.tw.dl.datasource.u}
spring.datasource.twdl.password=${app.env.tw.dl.datasource.p}
spring.datasource.twdl.pool-name=twdl-pool-cmn
spring.datasource.twdl.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.twdl.type=com.zaxxer.hikari.HikariDataSource

spring.datasource.twpr.connection-timeout=20000
spring.datasource.twpr.minimum-idle=10
spring.datasource.twpr.maximum-pool-size=10
spring.datasource.twpr.idle-timeout=10000
spring.datasource.twpr.max-lifetime=1000
spring.datasource.twpr.auto-commit=true
spring.datasource.twpr.jdbc-url=${app.env.tw.pr.datasource.url}
spring.datasource.twpr.username=${app.env.tw.pr.datasource.u}
spring.datasource.twpr.password=${app.env.tw.pr.datasource.p}
spring.datasource.twpr.pool-name=twpr-pool-cmn
spring.datasource.twpr.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.twpr.type=com.zaxxer.hikari.HikariDataSource

app.env.ldap.authorities.populator.strategy=recursive
spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true

springfox.documentation.swagger.use-model-v3=false

# oauth2 spring security
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${app.env.security.oauth2.jwk-set-uri}
security.oauth2.proxy.url=${security.oauth2.proxy.url}
security.oauth2.proxy.port=${security.oauth2.proxy.port}
security.oauth2.proxy.usr=${security.oauth2.proxy.usr}
security.oauth2.proxy.pass=${security.oauth2.proxy.pass}
security.oauth2.timeout=${security.oauth2.timeout}

# be
app.sms.username=${app.sms.username}
app.sms.password=${app.sms.password}
app.sms.ceco=${app.sms.ceco}

app.env.infplyMov.url=${app.env.infplyMov.url}
app.env.infplyMov.auth=${app.env.infplyMov.auth}
app.env.infplyMov.password=${app.env.infplyMov.password}

app.env.documentum.query.url=${app.env.documentum.query.url}
app.env.documentum.query.username=${app.env.documentum.query.username}
app.env.documentum.query.password=${app.env.documentum.query.password}
app.env.documentum.query.profile=${app.env.documentum.query.profile}
app.env.documentum.query.repository=${app.env.documentum.query.repository}
app.env.documentum.ply.document.type=${app.env.documentum.ply.document.type}
app.env.documentum.qtn.document.type=${app.env.documentum.qtn.document.type}

app.env.brwcncdbx.url=${app.env.brwcncdbx.url}
app.env.brwcncdbx.usuario=${app.env.brwcncdbx.usuario}
app.env.brwcncdbx.password=${app.env.brwcncdbx.password}

app.env.platea.url=${app.env.platea.url}
app.env.platea.username=${app.env.platea.username}
app.env.platea.password=${app.env.platea.password}

app.env.reportD2.endpoint=${app.env.reportD2.endpoint}

#
#These properties define the path and credentials to call to TRON API THP
#
app.env.tron.api.thp.basePath=${app.env.tron.api.thp.basePath}
app.env.tron.api.thp.userName=${app.env.tron.api.thp.userName}
app.env.tron.api.thp.password=${app.env.tron.api.thp.password}

#These properties define the path and credentials to call to TRON ISU API
app.env.tron.api.isu.basePath=${app.env.tron.api.isu.basePath}
app.env.tron.api.isu.userName=${app.env.tron.api.isu.userName}
app.env.tron.api.isu.password=${app.env.tron.api.isu.password}

#These properties define the path and credentials to call to TRON TSY API
app.env.tron.api.tsy.basePath=${app.env.tron.api.tsy.basePath}
app.env.tron.api.tsy.userName=${app.env.tron.api.tsy.userName}
app.env.tron.api.tsy.password=${app.env.tron.api.tsy.password}

#These properties define the path and credentials to call Risk selection service
app.env.risksel.basePath=${app.env.risksel.basePath}

server.port=8082
