# []
YES=S
# []
NO=N
# Formato de fecha extendido
DAT_FRM_EXT=N
# Formato fecha sin separador
FRM_DAT_WIT_SPR=ddMMyyyy
# Formato fecha con separador
FRM_DAT_WTH_SPR=dd/MM/yyyy
# Formato fecha corto
FRM_SHR_DAT_WIT_SPR=MMyy
# Formato año de una fecha
FRM_DAT_YER=yyyy
# Formato corto año de una fecha
FRM_SHR_DAT_YER=yy
# Formato mes de una fecha
FRM_DAT_MNH=MM
# Formato hora 24
FRM_DAT_HOR=HH
# Formato año-mes de una fecha
FRM_DAT_YER_MNH=yyyyMM
# Formato fecha-hora de una fecha
FRM_DAT_TME_WIT_SPR=ddMMyyyyHHmmss
# Formato hora de una fecha
FRM_TME_WIT_SPR=HHmmss
# Formato hora editado de una fecha
FRM_TME_EDT=HH:mm:ss
# Formato segundos de una fecha
FRM_DAT_SCN=SSSSS
# Multicuenta
MLC_VAL=S
# Separador de miles.
THS_SPR=,
# Separador de decimales.
DCL_SPR=.
# Instalacion.
INS_VAL=${app.ins.val}
# Base de datos.,
DBS_VAL=ORA
# Multitarjeta
MLR_VAL=N
# Variable para el numero maximo de registros en select
MAX_ROW_NMB=100
# Partition table
PAT_TBL=S
# Dia en que empieza la semana
BGN_DAY_WEK=1

MCA_MDT_THP_NEW=N
NBR_MXM_RSK_RNS=50
