app.env.spring.active.profile=demo with direct-connection
app.env.spring.active.profile.user=newtron-access
app.env.server.type=tomcat
gaia.env.rest.exceptionHanlder.enabled=true
app.env.soa.error.max-stack-trace-elements=5
app.env.name=nwt_cmn_api_be-web
app.env.nwt.datasource.ref.jndi=
app.env.nwt.datasource.url=jdbc:oracle:thin:@130.61.25.130:1521/radsomdb_fra1z6.sncontingencia.vcncontingencia.oraclevcn.com
app.env.nwt.datasource.u=NWT_APP
app.env.nwt.datasource.p=NWTAPP_DS04
app.env.tw.dl.datasource.ref.jndi=
app.env.tw.dl.datasource.url=jdbc:oracle:thin:@130.61.25.130:1521/radsomdb_fra1z6.sncontingencia.vcncontingencia.oraclevcn.com
app.env.tw.dl.datasource.u=TRON2000
app.env.tw.dl.datasource.p=TRON2000_15
app.env.tw.pr.datasource.ref.jndi=
app.env.tw.pr.datasource.url=jdbc:oracle:thin:@130.61.25.130:1521/radsomdb_fra1z6.sncontingencia.vcncontingencia.oraclevcn.com
app.env.tw.pr.datasource.u=TRON2000
app.env.tw.pr.datasource.p=TRON2000_15
app.env.report.endpoint=http://localhost:8080/report_be-web/api/reports/
app.system.info.project.version=${project.version}
app.system.info.be.version.dependency=${NEWTRON_BE_VERSION}