/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.api.cmn.sr;

import java.math.BigDecimal;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestParam;

import com.mapfre.nwt.exception.NwtException;
import com.mapfre.tron.api.cmn.men.bl.IBlCmnMenQry;
import com.mapfre.tron.api.cmn.model.MenuDto;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiParam;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;

/**
 * The Newtron menu controller.
 *
 * @author parlaga
 * @since 1.8
 * @version 08 mar. 2021 9:30:02
 *
 */
@Data
@Slf4j
@Controller
@Api(tags={ "Menu",})
public class MenuController implements MenuApi {

    @Autowired
    private IBlCmnMenQry blCmnMenQry;
    
    @Override
    public ResponseEntity<MenuDto> getMenu(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) Integer cmpVal,@NotNull @ApiParam(value = "Language code", required = true) @Valid @RequestParam(value = "lngVal", required = true) String lngVal,@NotNull @ApiParam(value = "User code", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal){
	log.info("The operation return menu is called...");
	       
	       try {
		   MenuDto menuDto = blCmnMenQry.getMenu(usrVal, lngVal, BigDecimal.valueOf(cmpVal));
			       
	           return ResponseEntity.ok(menuDto);
	       } catch (NwtException e) {
		   throw e;
	       }
    }
    
}
