#
# This file is used to define properties that change in different deployable environments.
#

# Environment name to be compared to source field of event header
app.env.description=${app.env.description}

# Application display name for Servlet-based applications
server.servlet.application-display-name=nwt_evn_be-web

spring.application.name=nwt_evn_be-web

# This property defines the active Spring profile.
app.env.spring.active.profile=${app.env.spring.active.profile}

# Required to overwrite mvc autoconfiguration bean
spring.main.allow-bean-definition-overriding = true

# Disable Spring Security
spring.security.enabled=false

# Use GSON json converter instead of default converter
spring.http.converters.preferred-json-mapper=gson

# Log level
#logging.level.root=DEBUG


#--------------------------
# Kafka auth configuration:
#--------------------------
spring.kafka.properties.bootstrap.servers=${EVENT_BROKER_SERVER}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=OAUTHBEARER
spring.kafka.properties.sasl.oauthbearer.token.endpoint.url=https://login.microsoftonline.com/${OAUTH_TENANT_ID}/oauth2/v2.0/token
spring.kafka.properties.sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId='${OAUTH_CLIENT_ID}' scope='${APPLICATION_REGISTRY_URI}' clientSecret='${OAUTH_CLIENT_SECRET}' extension_logicalCluster='${CLUSTER_ID}' extension_identityPoolId='${POOL_ID}';
spring.kafka.properties.bearer.auth.credentials.source=OAUTHBEARER
spring.kafka.properties.bearer.auth.issuer.endpoint.url=https://login.microsoftonline.com/${OAUTH_TENANT_ID}/oauth2/v2.0/token
spring.kafka.properties.bearer.auth.client.id=${OAUTH_CLIENT_ID}
spring.kafka.properties.bearer.auth.client.secret=${OAUTH_CLIENT_SECRET}
spring.kafka.properties.bearer.auth.scope=${APPLICATION_REGISTRY_URI}
spring.kafka.properties.bearer.auth.logical.cluster=${SCHEMA_REGISTRY_ID}
spring.kafka.properties.bearer.auth.identity.pool.id=${POOL_ID}

spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL}

# Proxy config only needed when executing inside a Mapfre VDI
spring.kafka.properties.schema.registry.proxy.host=proxy.glb.mapfre.net
spring.kafka.properties.schema.registry.proxy.port=80

# Tells Schema Registry that we will be using a specific Avro type, otherwise Kafka will expect GenericRecord to be used on the topic
spring.kafka.properties.specific.avro.reader=true

# Automatically commit offsets periodically (5s or value defined in auto.commit.interval.ms)
spring.kafka.consumer.enable-auto-commit=false

# read_committed consumer will only read up to the "Last Stable Offset" and filter out any transactional messages which have been aborted
spring.kafka.consumer.isolation.level=read_committed

# Whether to consume from the beginning of a topic partition (earliest) or to only consume new messages (latest) when there is no initial offset for the consumer group
spring.kafka.consumer.auto-offset-reset=earliest

# Specifies the deserializer class for consumer keys/values
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer

# Ensures that duplicates are not introduced due to unexpected retries
spring.kafka.producer.properties.enable.idempotence=true

# Prefix for transactional.id
spring.kafka.producer.transaction-id-prefix=tx-${random.uuid}

# Specifies the deserializer class for producer keys/values
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

#---------------
# Error handler:
#---------------

app.env.kafka.error.handler.interval=${app.env.kafka.error.handler.interval}
app.env.kafka.error.handler.retries=${app.env.kafka.error.handler.retries}


#--------------------------
# Synchronization consumer:
#--------------------------
# Sync consumer group
app.env.kafka.sync.insured.group=${app.env.kafka.sync.insured.group}

# topic id to listen to
app.env.kafka.topic.activity.id=${app.env.kafka.topic.activity.id}

# enable or disable this consumer
app.env.kafka.sync.insured.enabled=${app.env.kafka.sync.insured.enabled}


#---------------------
# Enrichment consumer:
#---------------------
# Enriching consumer group
app.env.kafka.enriching.insured.group=${app.env.kafka.enriching.insured.group}

# topic id to listen to
app.env.kafka.topic.insured.id=${app.env.kafka.topic.insured.id}

# enable or disable this consumer
app.env.kafka.enriching.insured.enabled=${app.env.kafka.enriching.insured.enabled}


#--------------------------------------------------
# Origin / Destination API REST related properties:
#--------------------------------------------------
app.env.tron.api.thp.endpointPath=/newtron/api/thirdparty
app.env.tron.api.thp.origin.basePath=https://trn.desa.mapfre.net/nwt_thp_api_be-web
app.env.tron.api.thp.origin.userName=${app.env.tron.api.thp.userName}
app.env.tron.api.thp.origin.password=${app.env.tron.api.thp.password}
app.env.tron.api.thp.destination.basePath=https://trn.pre.mapfre.net/nwt_thp_api_be-web
app.env.tron.api.thp.destination.userName=${app.env.tron.api.thp.userName}
app.env.tron.api.thp.destination.password=${app.env.tron.api.thp.password}

# Required data to read THP object from source API
app.env.tron.api.thp.origin.data.usrVal=TRONQA44
app.env.tron.api.thp.origin.data.lngVal=ES

# Required data to write THP object to target API
app.env.tron.api.thp.destination.data.usrVal=TRONQA44
app.env.tron.api.thp.destination.data.lngVal=ES


#-----------------------------
# Email service configuration:
#-----------------------------
app.mail.host=${app.mail.host}
app.mail.port=${app.mail.port}
app.mail.username=${app.mail.username}
app.mail.password=${app.mail.password}


#--------------------------------
# Error email message properties:
#--------------------------------
# Sender name
app.mail.from.name=${app.mail.from.name}

# Sender address (if not set, uses value of app.mail.username)
app.mail.from.address=${app.mail.from.address}

# addressees address and name (i.e. "{'someone@mapfre.net':'Someone','another@mapfre.net':'Another'}")
app.mail.to=${app.mail.to}

# Subject
app.mail.subject=${app.mail.subject}

# Content of the email body to which <object_failed_to_sync>.toString() will be concatenated
app.mail.content=${app.mail.content}
