/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.sfv.sr;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mapfre.tron.sfv.bo.SfvIn;
import com.mapfre.tron.sfv.bo.SfvOut;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@Api(value = "validateStep", description = "the validateStep API")
@RequestMapping(value = "/newtron/api/common")
public interface ValidateStepApi {

    Logger log = LoggerFactory.getLogger(ValidateStepApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Validate Screen Information", nickname = "postValidateStep", notes = "Validate information sended from frontal. It will be mandatory send the parameters defined in the service and the service will response with the output object defined.", response = SfvOut.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Validate Step", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Output structure data", response = SfvOut.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 404, message = "Not found", response = Error.class),
        @ApiResponse(code = 500, message = "Uncontrolled error", response = Error.class) })
    @RequestMapping(value = "/validateStep",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<SfvOut> postValidateStep(@NotNull @ApiParam(value = "Company code", required = true) @Valid @RequestParam(value = "cmpVal", required = true) BigDecimal cmpVal,@NotNull @ApiParam(value = "User value", required = true) @Valid @RequestParam(value = "usrVal", required = true) String usrVal,@ApiParam(value = "Language code" ,required=true) @RequestHeader(value="lngVal", required=true) String lngVal,@ApiParam(value = "Input structure data (agent, channel ...)" ,required=true )  @Valid @RequestBody SfvIn sfvIn) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"navigation\" : {    \"nxtSteIdn\" : \"step2\",    \"pmnNvgWhtPrrSte\" : false,    \"pmnNvgPrrSte\" : true  },  \"lngVal\" : \"lngVal\",  \"flwIdn\" : \"smn\",  \"cmpVal\" : 0.80082819046101150206595775671303272247314453125,  \"messages\" : [ {    \"fldNam\" : \"thpDcmVal\",    \"msgVal\" : 20001,    \"msgTxtVal\" : \"NO EXITS\",    \"msgTypVal\" : \"0-error, 1-info, 2-success\"  }, {    \"fldNam\" : \"thpDcmVal\",    \"msgVal\" : 20001,    \"msgTxtVal\" : \"NO EXITS\",    \"msgTypVal\" : \"0-error, 1-info, 2-success\"  } ],  \"parameters\" : {    \"key\" : \"parameters\"  }}", SfvOut.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ValidateStepApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
