appender.stdout.pattern=[%d{yyyy-MM-dd HH:mm:ss.SSS}] [sessionId:%X{sessionId:-not informed}] [requestId:%X{requestId:-not informed}] [remoteUser:%X{remoteUser:-not informed}] [%thread] %-5level %logger - %msg%n
appender.file.name=c:/tmp/LOGS_GAIA/nwt_cmn_api.log
appender.file.pattern=[%d{yyyy-MM-dd HH:mm:ss.SSS}] [sessionId:%X{sessionId:-not informed}] [requestId:%X{requestId:-not informed}] [remoteUser:%X{remoteUser:-not informed}] [%thread] %-5level %logger - %msg%n
appender.file.rollingpolicy.filenamepattern=c:/tmp/LOGS_GAIA/nwt_cmn_api.%d{yyyy-MM-dd}-%i.log
appender.file.maxsize=20MB
appender.file.jdbcobjects.name=c:/tmp/LOGS_GAIA/nwt_cmn_api-jdbcobjects.log
appender.file.jdbcobjects.pattern=[%d{yyyy-MM-dd HH:mm:ss.SSS}] [sessionId:%X{sessionId:-not informed}] [requestId:%X{requestId:-not informed}] [remoteUser:%X{remoteUser:-not informed}] [%thread] %-5level %logger - %msg%n
appender.file.jdbcobjects.rollingpolicy.filenamepattern=c:/tmp/LOGS_GAIA/nwt_cmn_api-jdbcobjects.%d{yyyy-MM-dd}-%i.log
appender.file.jdbcobjects.maxsize=100MB
appender.file.thirdparty.name=c:/tmp/LOGS_GAIA/nwt_cmn_api-thirdparty.log
appender.file.thirdparty.pattern=[%d{yyyy-MM-dd HH:mm:ss.SSS}] [sessionId:%X{sessionId:-not informed}] [requestId:%X{requestId:-not informed}] [remoteUser:%X{remoteUser:-not informed}] [%thread] %-5level %logger - %msg%n
appender.file.thirdparty.rollingpolicy.filenamepattern=c:/tmp/LOGS_GAIA/nwt_cmn_api-thirdparty.%d{yyyy-MM-dd}-%i.log
appender.file.thirdparty.maxsize=20MB
logger.root.level=INFO
logger.com.mapfre.level=WARN
logger.gaia.connector.level=WARN