/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.gdc.sr;

import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import com.mapfre.tron.gdc.sr.dto.DataIn;
import com.mapfre.tron.gdc.sr.dto.DefaultValue;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-07-13T11:40:05.311Z[GMT]")
@Api(value = "default", description = "the default API")
@RequestMapping(value = "/gdc")
public interface DefaultApi {

    @ApiOperation(value = "", nickname = "defaultValue", notes = "Get the default value for a field", response = DefaultValue.class, tags={ "Default", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK response", response = DefaultValue.class) })
    @RequestMapping(value = "/default/{idConcept}/field/{idField}",
        produces = { "application/json;charset=UTF-8" }, 
        consumes = { "application/json;charset=UTF-8" },
        method = RequestMethod.POST)
    ResponseEntity<DefaultValue> defaultValue(@ApiParam(value = "Data input including user info" ,required=true )  @Valid @RequestBody DataIn body
,@ApiParam(value = "Concept ID",required=true) @PathVariable("idConcept") String idConcept
,@ApiParam(value = "Field ID",required=true) @PathVariable("idField") String idField
);

}
