/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.gdc.sr;


import java.util.List;
import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import com.mapfre.tron.gdc.sr.dto.DataIn;
import com.mapfre.tron.gdc.sr.dto.FlowMdIn;
import com.mapfre.tron.gdc.sr.dto.FlowMdValue;
import com.mapfre.tron.gdc.sr.dto.ValidationError;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-08-11T07:20:33.285Z[GMT]")
@Api(value = "flow-md", description = "the flow-md API")
@RequestMapping(value = "/gdc")
public interface FlowMdApi {

    @ApiOperation(value = "", nickname = "flowMdAction", notes = "Perform final action in a flow-md screen", response = ValidationError.class, responseContainer = "List", tags={ "Flow-md", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK response", response = ValidationError.class, responseContainer = "List") })
    @RequestMapping(value = "/composition/{idComposition}/{idStep}/action",
        produces = { "application/json;charset=UTF-8" }, 
        consumes = { "application/json;charset=UTF-8" },
        method = RequestMethod.POST)
    ResponseEntity<List<ValidationError>> flowMdAction(@ApiParam(value = "Flow ID",required=true) @PathVariable("idComposition") String idComposition,
        @ApiParam(value = "Flow ID",required=true) @PathVariable("idStep") Integer idStep
,@ApiParam(value = "Data input including user info and screen data" ,required=true )  @Valid @RequestBody FlowMdIn body
);


    @ApiOperation(value = "", nickname = "flowMdPrevious", notes = "Load initial data in a flow-md screen", response = FlowMdValue.class, responseContainer = "List", tags={ "Flow-md", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK response", response = FlowMdValue.class, responseContainer = "List") })
    @RequestMapping(value = "/composition/{idComposition}/{idStep}/previous",
        produces = { "application/json;charset=UTF-8" }, 
        consumes = { "application/json;charset=UTF-8" },
        method = RequestMethod.POST)
    ResponseEntity<List<FlowMdValue>> flowMdPrevious(@ApiParam(value = "Flow ID",required=true) @PathVariable("idComposition") String idComposition,
        @ApiParam(value = "Flow ID",required=true) @PathVariable("idStep") Integer idStep
,@ApiParam(value = "Data input including user info" ,required=true )  @Valid @RequestBody DataIn body
);

}

