/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.gdc.sr;

import java.util.List;
import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.mapfre.tron.gdc.sr.dto.DataIn;
import com.mapfre.tron.gdc.sr.dto.HelpValue;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-07-13T11:40:05.311Z[GMT]")
@Api(value = "help", description = "the help API")
@RequestMapping(value = "/gdc")
public interface HelpApi {

    @ApiOperation(value = "", nickname = "help", notes = "Get help values depending on user values", response = HelpValue.class, responseContainer = "List", tags={ "Help", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK response", response = HelpValue.class, responseContainer = "List") })
    @RequestMapping(value = "/help/{idHelp}",
        produces = { "application/json;charset=UTF-8" }, 
        consumes = { "application/json;charset=UTF-8" },
        method = RequestMethod.POST)
    ResponseEntity<List<HelpValue>> help(@ApiParam(value = "Data input including user form and user info" ,required=true )  @Valid @RequestBody DataIn body
,@ApiParam(value = "ID of the help request",required=true) @PathVariable("idHelp") String idHelp, @ApiParam(value = "Company code", required = false) @Valid @RequestParam(value = "cmpVal", required = false) Integer cmpVal
);

}
