/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mapfre.tron.gdc.sr;

import java.util.List;
import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import com.mapfre.tron.gdc.sr.dto.DataIn;
import com.mapfre.tron.gdc.sr.dto.DataInExtended;
import com.mapfre.tron.gdc.sr.dto.ValidationError;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-07-13T11:40:05.311Z[GMT]")
@Api(value = "validation", description = "the validation API")
public interface ValidationApi {

    @ApiOperation(value = "", nickname = "conceptValidation", notes = "Validate a concept", response = ValidationError.class, responseContainer = "List", tags={ "Validation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK response", response = ValidationError.class, responseContainer = "List") })
    @RequestMapping(value = "/validation/{idConcept}",
        produces = { "application/json;charset=UTF-8" }, 
        consumes = { "application/json;charset=UTF-8" },
        method = RequestMethod.POST)
    ResponseEntity<List<ValidationError>> conceptValidation(@ApiParam(value = "Data input including user form and user info" ,required=true )  @Valid @RequestBody DataInExtended body
,@ApiParam(value = "Concept ID",required=true) @PathVariable("idConcept") String idConcept
);


    @ApiOperation(value = "", nickname = "fieldValidation", notes = "Validate a field", response = ValidationError.class, responseContainer = "List", tags={ "Validation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "default response", response = ValidationError.class, responseContainer = "List") })
    @RequestMapping(value = "/validation/{idConcept}/field/{idField}",
        produces = { "application/json;charset=UTF-8" }, 
        consumes = { "application/json;charset=UTF-8" },
        method = RequestMethod.POST)
    ResponseEntity<List<ValidationError>> fieldValidation(@ApiParam(value = "Data input including user form and user info" ,required=true )  @Valid @RequestBody DataIn body
,@ApiParam(value = "Concept ID",required=true) @PathVariable("idConcept") String idConcept
,@ApiParam(value = "Field ID",required=true) @PathVariable("idField") String idField
);


    @ApiOperation(value = "", nickname = "flowValidation", notes = "Validate a flow", response = ValidationError.class, responseContainer = "List", tags={ "Validation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK response", response = ValidationError.class, responseContainer = "List") })
    @RequestMapping(value = "/validation/flow/{idFlow}",
        produces = { "application/json;charset=UTF-8" }, 
        consumes = { "application/json;charset=UTF-8" },
        method = RequestMethod.POST)
    ResponseEntity<List<ValidationError>> flowValidation(@ApiParam(value = "Data input including user form and user info" ,required=true )  @Valid @RequestBody DataIn body
,@ApiParam(value = "Flow ID",required=true) @PathVariable("idFlow") String idFlow
);

}
